"""
gen_dao_docx.py — Dossier d'Appel d'Offres (DAO) as Word (.docx)
Tijan AI — BOQ table per lot (structure, mep, finitions) — NO PRICES
"""
import io
import math
import logging
from docx import Document
from docx.shared import Pt, Cm, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

logger = logging.getLogger(__name__)

# Tijan theme colors
VERT = RGBColor(0x43, 0xA9, 0x56)
BLANC = RGBColor(0xFF, 0xFF, 0xFF)
GRIS = RGBColor(0x55, 0x55, 0x55)
NOIR = RGBColor(0x11, 0x11, 0x11)

# ── I18N ──────────────────────────────────────────────────────
_T = {
    "fr": {
        "dao_title": "DOSSIER D'APPEL D'OFFRES",
        "lot_structure": "LOT STRUCTURE — GROS OEUVRE",
        "lot_mep": "LOT MEP — CORPS D'ÉTAT TECHNIQUES",
        "lot_finitions": "LOT FINITIONS — SECOND OEUVRE",
        "boq_title": "BORDEREAU DES QUANTITÉS",
        "col_no": "N°",
        "col_desig": "Désignation",
        "col_qty": "Quantité",
        "col_unit": "Unité",
        "col_obs": "Observations",
        "project": "Projet",
        "location": "Localisation",
        "surface": "Surface bâtie",
        "levels": "Niveaux",
        "generated_by": "Document généré par Tijan AI — tijan.ai",
    },
    "en": {
        "dao_title": "TENDER DOCUMENT",
        "lot_structure": "STRUCTURAL LOT — MAIN WORKS",
        "lot_mep": "MEP LOT — TECHNICAL TRADES",
        "lot_finitions": "FINISHES LOT — SECONDARY WORKS",
        "boq_title": "BILL OF QUANTITIES",
        "col_no": "No.",
        "col_desig": "Description",
        "col_qty": "Quantity",
        "col_unit": "Unit",
        "col_obs": "Notes",
        "project": "Project",
        "location": "Location",
        "surface": "Built area",
        "levels": "Levels",
        "generated_by": "Document generated by Tijan AI — tijan.ai",
    },
}

_LOT_KEYS = {
    "structure": "lot_structure",
    "mep": "lot_mep",
    "finitions": "lot_finitions",
}

_USAGE_LABELS = {
    "residentiel": {"fr": "Résidentiel", "en": "Residential"},
    "bureau":      {"fr": "Bureau",      "en": "Office"},
    "hotel":       {"fr": "Hôtel",       "en": "Hotel"},
    "mixte":       {"fr": "Mixte",       "en": "Mixed-use"},
    "commercial":  {"fr": "Commercial",  "en": "Commercial"},
    "industriel":  {"fr": "Industriel",  "en": "Industrial"},
}


def _t(key, lang="fr"):
    return _T.get(lang, _T["fr"]).get(key, key)


def _set_cell_background(cell, color_hex):
    shading = cell._element.get_or_add_tcPr()
    shading_elm = OxmlElement('w:shd')
    shading_elm.set(qn('w:fill'), color_hex)
    shading.append(shading_elm)


def _add_styled_table(doc, headers, rows, col_widths=None, header_color='43A956', zebra=False):
    table = doc.add_table(rows=1 + len(rows), cols=len(headers))
    table.style = 'Table Grid'
    table.alignment = WD_TABLE_ALIGNMENT.CENTER

    if col_widths:
        for i, w in enumerate(col_widths):
            for row in table.rows:
                row.cells[i].width = Cm(w)

    for i, h in enumerate(headers):
        cell = table.rows[0].cells[i]
        cell.text = str(h)
        p = cell.paragraphs[0]
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.runs[0]
        run.bold = True
        run.font.size = Pt(9)
        run.font.color.rgb = BLANC
        run.font.name = 'Calibri'
        _set_cell_background(cell, header_color)

    for r_idx, row_data in enumerate(rows):
        row = table.rows[r_idx + 1]
        for c_idx, val in enumerate(row_data):
            cell = row.cells[c_idx]
            cell.text = str(val)
            p = cell.paragraphs[0]
            run = p.runs[0] if p.runs else p.add_run(str(val))
            run.font.size = Pt(8)
            run.font.name = 'Calibri'
            if zebra and r_idx % 2 == 0:
                _set_cell_background(cell, 'F5F5F5')

    return table


# ══════════════════════════════════════════════════════════════
# BOQ BUILDERS (simplified — quantities only, no prices)
# ══════════════════════════════════════════════════════════════

def _boq_structure_items(rs, params):
    """Build structure BOQ items: list of (no, desig, qty, unit, obs)."""
    d = rs.params
    boq = rs.boq
    fond = rs.fondation
    dalle = rs.dalle
    poutre = rs.poutre_principale
    poteaux = rs.poteaux
    cl = rs.cloisons
    nb_pot = (d.nb_travees_x + 1) * (d.nb_travees_y + 1)
    ep_dalle_m = dalle.epaisseur_mm / 1000
    surf_batie = boq.surface_batie_m2
    perim = 4 * math.sqrt(d.surface_emprise_m2)

    items = []

    # Installation
    items.append(("1.1", "Cloture de chantier", int(perim), "ml", ""))
    items.append(("1.2", "Base vie chantier", 1, "fft", "Modulaires"))
    items.append(("1.3", "Branchements provisoires", 1, "fft", ""))

    # Terrassement
    V_fouilles = d.surface_emprise_m2 * (fond.profondeur_m + 0.50)
    items.append(("2.1", "Decapage terre vegetale e=30cm", int(d.surface_emprise_m2 * 0.30), "m3", ""))
    items.append(("2.2", "Fouilles generales mecaniques", int(V_fouilles), "m3", ""))
    items.append(("2.3", "Remblai compacte", int(V_fouilles * 0.30), "m3", ""))
    items.append(("2.4", "Evacuation terres", int(V_fouilles * 0.70), "m3", ""))

    # Fondations
    if fond.nb_pieux > 0:
        items.append(("3.1", f"Pieux fores D{fond.diam_pieu_mm}mm L={fond.longueur_pieu_m}m",
                       int(fond.nb_pieux * fond.longueur_pieu_m), "ml", f"{fond.nb_pieux} pieux"))
        items.append(("3.2", f"Armatures pieux {rs.classe_acier}",
                       int(fond.nb_pieux * fond.As_cm2 / 10000 * 7850 * fond.longueur_pieu_m), "kg", ""))
        items.append(("3.3", "Longrines BA 30x50cm", int(nb_pot * 6), "ml", ""))
    elif fond.beton_semelle_m3 > 0:
        items.append(("3.1", f"Semelles beton arme {rs.classe_beton}",
                       int(fond.beton_semelle_m3 * 0.6), "m3", ""))
        items.append(("3.2", f"Armatures semelles {rs.classe_acier}",
                       int(fond.beton_semelle_m3 * 100), "kg", ""))

    # Structure BA — poteaux
    for i, pt in enumerate(poteaux):
        items.append((f"4.1.{i+1}",
                       f"Poteaux {pt.niveau} {pt.section_mm}x{pt.section_mm}mm {pt.nb_barres}HA{pt.diametre_mm}",
                       nb_pot, "U", f"NEd={pt.NEd_kN:.0f}kN"))

    # Poutres
    b_p = poutre.b_mm / 1000
    h_p = poutre.h_mm / 1000
    L_px = d.nb_travees_x * d.portee_max_m * (d.nb_travees_y + 1) * d.nb_niveaux
    L_py = d.nb_travees_y * d.portee_min_m * (d.nb_travees_x + 1) * d.nb_niveaux
    V_pout = (L_px + L_py) * b_p * (h_p - ep_dalle_m)

    items.append(("4.2", f"Poutres principales {poutre.b_mm}x{poutre.h_mm}mm", int(L_px), "ml", ""))
    items.append(("4.3", f"Poutres secondaires {poutre.b_mm}x{poutre.h_mm}mm", int(L_py), "ml", ""))
    items.append(("4.4", f"Armatures poutres {rs.classe_acier}", int(V_pout * 100), "kg", ""))

    # Dalles
    V_dalles = surf_batie * ep_dalle_m * 0.85
    items.append(("4.5", f"Beton dalles {rs.classe_beton} e={dalle.epaisseur_mm}mm", int(V_dalles), "m3", ""))
    items.append(("4.6", f"Armatures dalles {rs.classe_acier}", int(V_dalles * 80), "kg", ""))
    items.append(("4.7", "Coffrage dalles", int(surf_batie * 0.85), "m2", ""))

    # Escaliers
    nb_esc = max(1, int(surf_batie / 1500))
    items.append(("4.8", f"Escaliers beton arme {rs.classe_beton}", nb_esc * d.nb_niveaux, "volee", f"{nb_esc} cage(s)"))

    # Maconnerie
    surf_facades = int(4 * math.sqrt(d.surface_emprise_m2) * d.nb_niveaux * d.hauteur_etage_m * 0.70)
    items.append(("5.1", "Maconnerie facades agglos pleins 25cm", surf_facades, "m2", ""))
    items.append(("5.2", "Cloisons separatives", int(cl.surface_separative_m2), "m2", ""))
    items.append(("5.3", "Cloisons legeres BA13", int(cl.surface_legere_m2), "m2", ""))
    items.append(("5.4", "Enduits ciment + platre", int((surf_facades + cl.surface_separative_m2) * 2), "m2", ""))

    # Etancheite
    items.append(("6.1", "Etancheite toiture-terrasse SBS", int(d.surface_emprise_m2), "m2", "DTU 43.1"))
    items.append(("6.2", "Etancheite salles de bains", int(surf_batie * 0.08), "m2", ""))

    return items


def _boq_mep_items(rs_mep, params):
    """Build MEP BOQ items."""
    d = rs_mep.params
    surf_batie = rs_mep.surf_batie_m2
    nb_log = rs_mep.nb_logements
    nb_niveaux = d.nb_niveaux
    surface_emprise = getattr(d, 'surface_emprise_m2', 500)
    perim = 4 * math.sqrt(surface_emprise)

    items = []

    # Electricite
    items.append(("1.1", "TGBT complet", 1, "fft", ""))
    items.append(("1.2", "Compteurs monophases", nb_log, "U", "Par logement"))
    items.append(("1.3", "Cablage cuivre distribution", int(surf_batie * 0.8), "ml", ""))
    items.append(("1.4", "Luminaires LED standard", int(surf_batie / 8), "U", "1 / 8m2"))

    # Plomberie
    items.append(("2.1", "Colonnes montantes acier galva", int(nb_niveaux * 2), "ml", ""))
    items.append(("2.2", "Tuyauterie PVC DN100 EU/EV", int(surf_batie * 0.3), "ml", ""))
    items.append(("2.3", "WC double chasse 3/6L", int(nb_log * 1.5), "U", ""))
    items.append(("2.4", "Robinets economiques", int(nb_log * 3), "U", ""))
    items.append(("2.5", "Cuve eau 10000L", max(1, int(surf_batie / 3000)), "U", ""))
    items.append(("2.6", "Pompe surpresseur", 1, "U", ""))

    # CVC
    nb_splits_1cv = int(surf_batie * 0.4 / 15)
    nb_splits_2cv = int(surf_batie * 0.3 / 25)
    items.append(("3.1", "Splits muraux 1CV (9000 BTU)", nb_splits_1cv, "U", "Chambres"))
    items.append(("3.2", "Splits muraux 2CV (18000 BTU)", nb_splits_2cv, "U", "Sejours"))
    items.append(("3.3", "VMC simple flux", nb_log, "U", "Par logement"))

    # Courants faibles
    items.append(("4.1", "Cablage reseau RJ45 Cat6", int(surf_batie * 0.3), "ml", ""))
    items.append(("4.2", "Prises reseau RJ45", int(nb_log * 3), "U", "3 / logement"))
    items.append(("4.3", "Baie serveur 12U", max(1, int(surf_batie / 5000)), "U", ""))
    items.append(("4.4", "Cameras IP exterieures", max(4, int(perim / 15)), "U", "1 / 15ml"))
    items.append(("4.5", "Interphone video", nb_log, "U", "Par logement"))

    # Securite incendie
    items.append(("5.1", "Detecteurs fumee optiques", int(surf_batie / 30), "U", "1 / 30m2"))
    items.append(("5.2", "Declencheurs manuels", nb_niveaux * 2, "U", "2 / niveau"))
    items.append(("5.3", "Sirenes + flash", nb_niveaux, "U", "1 / niveau"))
    items.append(("5.4", "Centrale incendie", 1, "U", ""))
    items.append(("5.5", "Extincteurs CO2 6kg", nb_niveaux * 2, "U", "2 / niveau"))
    items.append(("5.6", "Extincteurs poudre 9kg", nb_niveaux * 2, "U", "2 / niveau"))
    items.append(("5.7", "RIA DN25", int(nb_niveaux * 15), "ml", "IT 246"))

    # Ascenseurs
    asc = rs_mep.ascenseurs
    nb_asc = getattr(asc, "nb_ascenseurs", 0) or (1 if nb_niveaux >= 4 else 0)
    if nb_asc > 0:
        items.append(("6.1", f"Ascenseur 630kg {nb_niveaux} niveaux", nb_asc, "U", "EN 81-20"))

    return items


def _boq_finitions_items(rs_structure, params):
    """Build finitions BOQ items."""
    d = rs_structure.params if rs_structure else None
    surface_emprise = params.get("surface_emprise_m2",
                                  getattr(d, "surface_emprise_m2", 500) if d else 500)
    nb_niveaux = params.get("nb_niveaux",
                             getattr(d, "nb_niveaux", 5) if d else 5)
    surf_batie = surface_emprise * nb_niveaux
    perim = 4 * math.sqrt(surface_emprise)

    items = []

    # Carrelage
    items.append(("1.1", "Gres cerame 60x60 pose incluse", int(surf_batie * 1.0), "m2", ""))

    # Menuiserie interieure
    nb_portes = int(surf_batie / 100 * 4.5)
    items.append(("2.1", "Portes bois + huisseries", nb_portes, "U", ""))

    # Menuiserie exterieure
    surf_vitrages = int(perim * nb_niveaux * 3.0 * 0.18)
    items.append(("3.1", "Fenetres aluminium double vitrage", surf_vitrages, "m2", ""))

    # Faux-plafonds
    items.append(("4.1", "Faux-plafonds BA13 / staff decoratif", int(surf_batie * 0.75), "m2", ""))

    # Peinture
    surf_peinte = int(surf_batie * (2.8 + 1.0))
    items.append(("5.1", "Peinture acrylique 3 couches", surf_peinte, "m2", ""))

    # Cuisine
    ml_cuisine = int(surf_batie / 100 * 2.5)
    items.append(("6.1", "Cuisines equipees completes", ml_cuisine, "ml", ""))

    return items


# ══════════════════════════════════════════════════════════════
# MAIN GENERATOR
# ══════════════════════════════════════════════════════════════

def generer_dao_docx(rs_structure, rs_mep, params, lot='structure', lang='fr') -> bytes:
    """
    Generate DAO (Dossier d'Appel d'Offres) as Word (.docx).
    BOQ table with quantities only — NO PRICES.

    Args:
        rs_structure: ResultatsStructure object
        rs_mep: ResultatsMEP object
        params: dict of project parameters
        lot: 'structure', 'mep', or 'finitions'
        lang: 'fr' or 'en'

    Returns:
        bytes: DOCX document content
    """
    doc = Document()

    # Set default font
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(10)

    # ── COVER ──
    lot_key = _LOT_KEYS.get(lot, "lot_structure")
    lot_label = _t(lot_key, lang)

    title = doc.add_heading(_t("dao_title", lang), level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in title.runs:
        run.font.color.rgb = VERT
        run.font.size = Pt(18)
        run.font.name = 'Calibri'

    subtitle = doc.add_heading(lot_label, level=1)
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph()

    # Project info
    d = rs_structure.params if rs_structure else None
    nom = params.get("nom", getattr(d, "nom", "Projet Tijan") if d else "Projet Tijan")
    ville = params.get("ville", getattr(d, "ville", "Dakar") if d else "Dakar")
    nb_niveaux = params.get("nb_niveaux", getattr(d, "nb_niveaux", 5) if d else 5)
    surface_emprise = params.get("surface_emprise_m2",
                                  getattr(d, "surface_emprise_m2", 500) if d else 500)
    surf_batie = surface_emprise * nb_niveaux

    info_data = [
        [_t("project", lang), nom],
        [_t("location", lang), ville],
        [_t("surface", lang), f'{int(surf_batie):,} m²'.replace(',', ' ')],
        [_t("levels", lang), f'R+{nb_niveaux - 1} ({nb_niveaux})'],
    ]
    _add_styled_table(doc, ['', ''], info_data,
                      col_widths=[5.0, 12.0], header_color='43A956')

    doc.add_page_break()

    # ── BOQ TABLE ──
    doc.add_heading(_t("boq_title", lang), level=1)

    boq_headers = [
        _t("col_no", lang),
        _t("col_desig", lang),
        _t("col_qty", lang),
        _t("col_unit", lang),
        _t("col_obs", lang),
    ]

    if lot == 'structure':
        items = _boq_structure_items(rs_structure, params)
    elif lot == 'mep':
        items = _boq_mep_items(rs_mep, params)
    elif lot == 'finitions':
        items = _boq_finitions_items(rs_structure, params)
    else:
        items = []

    boq_rows = []
    for item in items:
        no, desig, qty, unit, obs = item
        boq_rows.append([
            str(no),
            str(desig),
            str(qty) if qty else '—',
            str(unit),
            str(obs) if obs else '',
        ])

    _add_styled_table(doc, boq_headers, boq_rows,
                      col_widths=[1.5, 7.5, 2.0, 1.5, 4.0],
                      header_color='43A956', zebra=True)

    doc.add_paragraph()

    # ── FOOTER ──
    footer_p = doc.add_paragraph(f'\n\n{_t("generated_by", lang)}')
    footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in footer_p.runs:
        run.font.size = Pt(8)
        run.font.italic = True
        run.font.color.rgb = GRIS
        run.font.name = 'Calibri'

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
