"""
gen_planning_docx.py — Planning d'execution + Plan de tresorerie as Word (.docx)
Tijan AI — Word output via python-docx
"""
import io
import logging
from docx import Document
from docx.shared import Pt, Inches, Cm, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

logger = logging.getLogger(__name__)

# Tijan theme colors
VERT = RGBColor(0x43, 0xA9, 0x56)
VERT_LIGHT = RGBColor(0xE8, 0xF5, 0xEA)
NAVY = RGBColor(0x1B, 0x2A, 0x4A)
NOIR = RGBColor(0x11, 0x11, 0x11)
GRIS = RGBColor(0x55, 0x55, 0x55)
BLANC = RGBColor(0xFF, 0xFF, 0xFF)
ORANGE = RGBColor(0xFF, 0xB3, 0x0F)

# ── I18N ──────────────────────────────────────────────────────
_T = {
    "fr": {
        "title_planning": "Planning d'exécution",
        "title_tresorerie": "Plan de Trésorerie",
        "project_info": "Informations projet",
        "nom": "Projet",
        "ville": "Ville",
        "niveaux": "Niveaux",
        "surface": "Surface bâtie",
        "duree": "Durée totale",
        "jours": "jours",
        "mois": "mois",
        "lot_structure": "STRUCTURE",
        "lot_mep": "MEP",
        "lot_finitions": "FINITIONS",
        "col_no": "N°",
        "col_tache": "Tâche",
        "col_duree": "Durée (j)",
        "col_debut": "Début (j)",
        "col_fin": "Fin (j)",
        "section_tasks": "Planning des tâches par lot",
        "tresorerie_mensuelle": "Trésorerie mensuelle",
        "col_mois": "Mois",
        "col_materiaux": "Matériaux",
        "col_mo": "Main d'œuvre",
        "col_total_mensuel": "Total mensuel",
        "col_cumul": "Cumul",
        "tresorerie_lot_phase": "Répartition par lot et phase",
        "col_lot": "Lot",
        "col_phase": "Phase",
        "col_cout": "Coût total",
        "total": "TOTAL",
        "generated_by": "Document généré par Tijan AI — tijan.ai",
    },
    "en": {
        "title_planning": "Execution Schedule",
        "title_tresorerie": "Cash Flow Plan",
        "project_info": "Project Information",
        "nom": "Project",
        "ville": "City",
        "niveaux": "Levels",
        "surface": "Built area",
        "duree": "Total duration",
        "jours": "days",
        "mois": "months",
        "lot_structure": "STRUCTURE",
        "lot_mep": "MEP",
        "lot_finitions": "FINISHES",
        "col_no": "No.",
        "col_tache": "Task",
        "col_duree": "Duration (d)",
        "col_debut": "Start (d)",
        "col_fin": "End (d)",
        "section_tasks": "Task schedule by lot",
        "tresorerie_mensuelle": "Monthly Cash Flow",
        "col_mois": "Month",
        "col_materiaux": "Materials",
        "col_mo": "Labor",
        "col_total_mensuel": "Monthly total",
        "col_cumul": "Cumulative",
        "tresorerie_lot_phase": "Breakdown by lot and phase",
        "col_lot": "Lot",
        "col_phase": "Phase",
        "col_cout": "Total cost",
        "total": "TOTAL",
        "generated_by": "Document generated by Tijan AI — tijan.ai",
    },
}


def _t(key, lang="fr"):
    return _T.get(lang, _T["fr"]).get(key, key)


def _fmt_fcfa(v):
    """Format value as FCFA currency."""
    if not v or v == 0:
        return '—'
    if v >= 1e9:
        return f"{v/1e9:.2f} Mds FCFA"
    if v >= 1e6:
        return f"{v/1e6:.1f} M FCFA"
    return f"{int(v):,} FCFA".replace(',', ' ')


def _set_cell_background(cell, color_hex):
    """Set cell background color."""
    shading = cell._element.get_or_add_tcPr()
    shading_elm = OxmlElement('w:shd')
    shading_elm.set(qn('w:fill'), color_hex)
    shading.append(shading_elm)


def _add_styled_table(doc, headers, rows, col_widths=None, header_color='43A956', zebra=False):
    """Add a professionally styled table with header row shading."""
    table = doc.add_table(rows=1 + len(rows), cols=len(headers))
    table.style = 'Table Grid'
    table.alignment = WD_TABLE_ALIGNMENT.CENTER

    if col_widths:
        for i, w in enumerate(col_widths):
            for row in table.rows:
                row.cells[i].width = Cm(w)

    # Header row
    for i, h in enumerate(headers):
        cell = table.rows[0].cells[i]
        cell.text = str(h)
        p = cell.paragraphs[0]
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.runs[0]
        run.bold = True
        run.font.size = Pt(9)
        run.font.color.rgb = BLANC
        run.font.name = 'Calibri'
        _set_cell_background(cell, header_color)

    # Data rows
    for r_idx, row_data in enumerate(rows):
        row = table.rows[r_idx + 1]
        for c_idx, val in enumerate(row_data):
            cell = row.cells[c_idx]
            cell.text = str(val)
            p = cell.paragraphs[0]
            run = p.runs[0] if p.runs else p.add_run(str(val))
            run.font.size = Pt(8)
            run.font.name = 'Calibri'
            if zebra and r_idx % 2 == 0:
                _set_cell_background(cell, 'F5F5F5')

    return table


def _add_title(doc, text, lang='fr'):
    """Add a green Tijan-style title."""
    title = doc.add_heading(text, level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in title.runs:
        run.font.color.rgb = VERT
        run.font.size = Pt(18)
        run.font.name = 'Calibri'


def _add_footer(doc, lang='fr'):
    """Add a Tijan footer."""
    footer_p = doc.add_paragraph(f'\n\n{_t("generated_by", lang)}')
    footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in footer_p.runs:
        run.font.size = Pt(8)
        run.font.italic = True
        run.font.color.rgb = GRIS
        run.font.name = 'Calibri'


# ══════════════════════════════════════════════════════════════
# PLANNING DOCX
# ══════════════════════════════════════════════════════════════

def generer_planning_docx(planning, lang='fr') -> bytes:
    """
    Generate Planning d'execution as Word (.docx).

    Args:
        planning: Planning object from engine_planning.py
        lang: 'fr' or 'en'

    Returns:
        bytes: DOCX document content
    """
    doc = Document()

    # Set default font
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(10)

    # ── TITLE ──
    _add_title(doc, _t("title_planning", lang), lang)

    # ── PROJECT INFO ──
    doc.add_heading(_t("project_info", lang), level=1)

    info_data = [
        [_t("nom", lang), planning.projet_nom],
        [_t("ville", lang), planning.ville],
        [_t("niveaux", lang), f'R+{planning.nb_niveaux - 1} ({planning.nb_niveaux} {_t("niveaux", lang).lower()})'],
        [_t("surface", lang), f'{int(planning.surface_batie_m2):,} m²'.replace(',', ' ')],
        [_t("duree", lang), f'{planning.duree_totale_jours} {_t("jours", lang)} ({planning.duree_totale_mois} {_t("mois", lang)})'],
    ]
    _add_styled_table(doc, [_t("project_info", lang), ''], info_data,
                      col_widths=[5.0, 12.0], header_color='43A956')

    doc.add_paragraph()

    # ── TASK LIST BY LOT ──
    doc.add_page_break()
    doc.add_heading(_t("section_tasks", lang), level=1)

    # Group tasks by lot
    lots = {}
    for tache in planning.taches:
        lot_key = tache.lot
        if lot_key not in lots:
            lots[lot_key] = []
        lots[lot_key].append(tache)

    lot_labels = {
        "STRUCTURE": _t("lot_structure", lang),
        "MEP": _t("lot_mep", lang),
        "FINITIONS": _t("lot_finitions", lang),
    }

    task_headers = [
        _t("col_no", lang),
        _t("col_tache", lang),
        _t("col_duree", lang),
        _t("col_debut", lang),
        _t("col_fin", lang),
    ]

    for lot_key in ["STRUCTURE", "MEP", "FINITIONS"]:
        taches = lots.get(lot_key, [])
        if not taches:
            continue

        lot_label = lot_labels.get(lot_key, lot_key)
        doc.add_heading(lot_label, level=2)

        task_rows = []
        for i, tache in enumerate(taches):
            task_rows.append([
                tache.id,
                tache.designation,
                str(tache.duree_jours),
                str(tache.debut_jour),
                str(tache.fin_jour),
            ])

        _add_styled_table(doc, task_headers, task_rows,
                          col_widths=[2.0, 8.0, 2.5, 2.5, 2.5],
                          header_color='43A956', zebra=True)

        doc.add_paragraph()

    # ── FOOTER ──
    _add_footer(doc, lang)

    # Save to bytes
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


# ══════════════════════════════════════════════════════════════
# TRESORERIE DOCX
# ══════════════════════════════════════════════════════════════

def generer_tresorerie_docx(planning, lang='fr') -> bytes:
    """
    Generate Plan de Tresorerie as Word (.docx).

    Args:
        planning: Planning object from engine_planning.py
        lang: 'fr' or 'en'

    Returns:
        bytes: DOCX document content
    """
    doc = Document()

    # Set default font
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(10)

    # ── TITLE ──
    _add_title(doc, _t("title_tresorerie", lang), lang)

    # ── PROJECT INFO ──
    doc.add_heading(_t("project_info", lang), level=1)

    info_data = [
        [_t("nom", lang), planning.projet_nom],
        [_t("ville", lang), planning.ville],
        [_t("surface", lang), f'{int(planning.surface_batie_m2):,} m²'.replace(',', ' ')],
        [_t("duree", lang), f'{planning.duree_totale_mois} {_t("mois", lang)}'],
    ]
    _add_styled_table(doc, [_t("project_info", lang), ''], info_data,
                      col_widths=[5.0, 12.0], header_color='43A956')

    doc.add_paragraph()

    # ── MONTHLY CASH FLOW TABLE ──
    doc.add_page_break()
    doc.add_heading(_t("tresorerie_mensuelle", lang), level=1)

    monthly_headers = [
        _t("col_mois", lang),
        _t("col_materiaux", lang),
        _t("col_mo", lang),
        _t("col_total_mensuel", lang),
        _t("col_cumul", lang),
    ]

    monthly_rows = []
    for m in planning.tresorerie_mensuelle:
        monthly_rows.append([
            str(m.get('mois', '')),
            _fmt_fcfa(m.get('depense_materiel_fcfa', 0)),
            _fmt_fcfa(m.get('depense_pose_fcfa', 0)),
            _fmt_fcfa(m.get('depense_total_fcfa', 0)),
            _fmt_fcfa(m.get('cumul_fcfa', 0)),
        ])

    # Add total row
    if planning.tresorerie_mensuelle:
        total_mat = sum(m.get('depense_materiel_fcfa', 0) for m in planning.tresorerie_mensuelle)
        total_pose = sum(m.get('depense_pose_fcfa', 0) for m in planning.tresorerie_mensuelle)
        monthly_rows.append([
            _t("total", lang),
            _fmt_fcfa(total_mat),
            _fmt_fcfa(total_pose),
            _fmt_fcfa(planning.cout_total_fcfa),
            _fmt_fcfa(planning.cout_total_fcfa),
        ])

    table = _add_styled_table(doc, monthly_headers, monthly_rows,
                              col_widths=[2.5, 3.5, 3.5, 3.5, 3.5],
                              header_color='43A956', zebra=True)

    # Bold the total row
    if monthly_rows:
        last_row = table.rows[-1]
        for cell in last_row.cells:
            _set_cell_background(cell, 'E8F5EA')
            for p in cell.paragraphs:
                for run in p.runs:
                    run.bold = True

    doc.add_paragraph()

    # ── LOT × PHASE CROSS-TAB ──
    doc.add_page_break()
    doc.add_heading(_t("tresorerie_lot_phase", lang), level=1)

    lp_headers = [
        _t("col_lot", lang),
        _t("col_phase", lang),
        _t("col_cout", lang),
    ]

    lp_rows = []
    total_lp = 0
    for item in planning.tresorerie_lot_phase:
        cout = item.get('cout_total_fcfa', 0)
        total_lp += cout
        lp_rows.append([
            str(item.get('lot', '')),
            str(item.get('phase', '')),
            _fmt_fcfa(cout),
        ])

    # Add total row
    lp_rows.append([
        _t("total", lang),
        '',
        _fmt_fcfa(total_lp),
    ])

    table_lp = _add_styled_table(doc, lp_headers, lp_rows,
                                 col_widths=[5.0, 6.0, 5.0],
                                 header_color='43A956', zebra=True)

    # Bold the total row
    if lp_rows:
        last_row = table_lp.rows[-1]
        for cell in last_row.cells:
            _set_cell_background(cell, 'E8F5EA')
            for p in cell.paragraphs:
                for run in p.runs:
                    run.bold = True

    doc.add_paragraph()

    # ── FOOTER ──
    _add_footer(doc, lang)

    # Save to bytes
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
