"""
gen_fiches_finitions_docx.py — Fiches techniques Finitions as Word (.docx)
Tijan AI — 6 fiches: carrelage, menuiserie int, menuiserie ext,
faux-plafonds, peinture, cuisine — NO PRICES
"""
import io
import logging
from docx import Document
from docx.shared import Pt, Cm, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

logger = logging.getLogger(__name__)

# Tijan theme colors
VERT = RGBColor(0x43, 0xA9, 0x56)
VERT_LIGHT = RGBColor(0xE8, 0xF5, 0xEA)
BLANC = RGBColor(0xFF, 0xFF, 0xFF)
GRIS = RGBColor(0x55, 0x55, 0x55)
NOIR = RGBColor(0x11, 0x11, 0x11)

# ── I18N ──────────────────────────────────────────────────────
_T = {
    "fr": {
        "title": "Fiches Techniques — Finitions",
        "specs": "Spécifications",
        "meo": "Mise en œuvre",
        "normes": "Normes applicables",
        "fournisseurs": "Fournisseurs de référence",
        "generated_by": "Document généré par Tijan AI — tijan.ai",
    },
    "en": {
        "title": "Technical Data Sheets — Finishes",
        "specs": "Specifications",
        "meo": "Implementation",
        "normes": "Applicable standards",
        "fournisseurs": "Reference suppliers",
        "generated_by": "Document generated by Tijan AI — tijan.ai",
    },
}


def _t(key, lang="fr"):
    return _T.get(lang, _T["fr"]).get(key, key)


def _set_cell_background(cell, color_hex):
    shading = cell._element.get_or_add_tcPr()
    shading_elm = OxmlElement('w:shd')
    shading_elm.set(qn('w:fill'), color_hex)
    shading.append(shading_elm)


def _add_specs_table(doc, specs, header_color='43A956'):
    """Add a 2-column specs table (label | value)."""
    table = doc.add_table(rows=len(specs), cols=2)
    table.style = 'Table Grid'
    table.alignment = WD_TABLE_ALIGNMENT.CENTER

    for row in table.rows:
        row.cells[0].width = Cm(6.0)
        row.cells[1].width = Cm(10.0)

    for r_idx, (label, value) in enumerate(specs):
        cell_label = table.rows[r_idx].cells[0]
        cell_value = table.rows[r_idx].cells[1]

        cell_label.text = str(label)
        cell_value.text = str(value)

        # Style label cell
        _set_cell_background(cell_label, 'E8F5EA')
        for p in cell_label.paragraphs:
            for run in p.runs:
                run.bold = True
                run.font.size = Pt(8)
                run.font.name = 'Calibri'

        # Style value cell
        for p in cell_value.paragraphs:
            for run in p.runs:
                run.font.size = Pt(8)
                run.font.name = 'Calibri'

        # Zebra
        if r_idx % 2 == 1:
            _set_cell_background(cell_value, 'F5F5F5')

    return table


def _add_fiche(doc, code, titre, norme_ref, specs, meo_items, fournisseurs, normes, lang='fr'):
    """Add a single fiche page to the document."""
    # Fiche header
    heading = doc.add_heading(f'{code} — {titre}', level=2)
    for run in heading.runs:
        run.font.color.rgb = VERT
        run.font.name = 'Calibri'

    # Norme reference
    norme_p = doc.add_paragraph(norme_ref)
    norme_p.paragraph_format.space_after = Pt(4)
    for run in norme_p.runs:
        run.font.size = Pt(8)
        run.font.italic = True
        run.font.color.rgb = GRIS
        run.font.name = 'Calibri'

    # Specs table
    doc.add_heading(_t("specs", lang), level=3)
    _add_specs_table(doc, specs)

    doc.add_paragraph()

    # Mise en oeuvre
    doc.add_heading(_t("meo", lang), level=3)
    for item in meo_items:
        p = doc.add_paragraph(item, style='List Bullet')
        for run in p.runs:
            run.font.size = Pt(8)
            run.font.name = 'Calibri'

    doc.add_paragraph()

    # Normes
    normes_p = doc.add_paragraph()
    run_label = normes_p.add_run(f'{_t("normes", lang)} : ')
    run_label.bold = True
    run_label.font.size = Pt(8)
    run_label.font.name = 'Calibri'
    run_value = normes_p.add_run(normes)
    run_value.font.size = Pt(8)
    run_value.font.name = 'Calibri'

    # Fournisseurs
    fourn_p = doc.add_paragraph()
    run_label = fourn_p.add_run(f'{_t("fournisseurs", lang)} : ')
    run_label.bold = True
    run_label.font.size = Pt(8)
    run_label.font.name = 'Calibri'
    run_value = fourn_p.add_run(fournisseurs)
    run_value.font.size = Pt(8)
    run_value.font.name = 'Calibri'

    doc.add_page_break()


# ══════════════════════════════════════════════════════════════
# MAIN GENERATOR
# ══════════════════════════════════════════════════════════════

def generer_fiches_finitions_docx(rs_structure, params, lang='fr') -> bytes:
    """
    Generate Fiches techniques Finitions as Word (.docx).
    6 fiches: carrelage, menuiserie int, menuiserie ext,
    faux-plafonds, peinture, cuisine — NO PRICES.

    Args:
        rs_structure: ResultatsStructure object
        params: dict of project parameters
        lang: 'fr' or 'en'

    Returns:
        bytes: DOCX document content
    """
    doc = Document()

    # Set default font
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(10)

    nom = params.get('nom', 'Projet Tijan')

    # ── TITLE PAGE ──
    title = doc.add_heading(nom, level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in title.runs:
        run.font.color.rgb = VERT
        run.font.size = Pt(18)
        run.font.name = 'Calibri'

    subtitle = doc.add_heading(_t("title", lang), level=1)
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

    desc_text = (
        "Specifications techniques, normes applicables et conseils de mise en oeuvre "
        "pour chaque poste de finition."
    ) if lang == 'fr' else (
        "Technical specifications, applicable standards and implementation guidance "
        "for each finishing item."
    )
    desc_p = doc.add_paragraph(desc_text)
    desc_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in desc_p.runs:
        run.font.size = Pt(9)
        run.font.italic = True
        run.font.color.rgb = GRIS
        run.font.name = 'Calibri'

    doc.add_page_break()

    # ── FIN-01 Carrelage ──
    _add_fiche(doc,
        code="FIN-01",
        titre="Carrelage" if lang == 'fr' else "Tiling",
        norme_ref="DTU 52.1 / NF EN 14411 / NF EN 12004 (colles)",
        specs=[
            ("Gres cerame" if lang == 'fr' else "Porcelain stoneware", "30x30, 45x45, 60x60 cm"),
            ("Faience murale" if lang == 'fr' else "Wall tiles", "20x25, 25x40, 30x60 cm"),
            ("Classement UPEC" if lang == 'fr' else "UPEC rating", "U3 P3 E2 C1 (residentiel)"),
            ("Resistance glissance" if lang == 'fr' else "Slip resistance", "R10 (int.), R11 (ext./SDB)"),
            ("Absorption eau" if lang == 'fr' else "Water absorption", "< 0.5% (gres cerame)"),
            ("Colle" if lang == 'fr' else "Adhesive", "C2TE (amelioree, double encollage)"),
            ("Joints" if lang == 'fr' else "Grout", "2-5 mm, hydrofuge en SDB"),
            ("Epaisseur" if lang == 'fr' else "Thickness", "8-10 mm (sol), 6-8 mm (mur)"),
        ],
        meo_items=[
            "Support propre, plan (tolerance 5 mm/2m), sec" if lang == 'fr' else "Clean, flat (5 mm/2m tolerance), dry substrate",
            "Primaire d'accrochage si support poreux" if lang == 'fr' else "Primer if porous substrate",
            "Double encollage obligatoire pour format >= 45x45 cm" if lang == 'fr' else "Double buttering mandatory for tiles >= 45x45 cm",
            "Joints de dilatation perimetriques + tous les 6 m" if lang == 'fr' else "Peripheral expansion joints + every 6 m",
            "Equipe: 1 carreleur + 1 aide / 10-15 m2/jour (sol)" if lang == 'fr' else "Crew: 1 tiler + 1 helper / 10-15 m2/day (floor)",
            "Reception: planeite 2 mm/2m, sonorite (pas de creux)" if lang == 'fr' else "Acceptance: flatness 2 mm/2m, tap test (no hollow)",
        ],
        fournisseurs="Porcelanosa, Marazzi, RAK Ceramics, importateurs Dakar (Comptoir du Carrelage)",
        normes="DTU 52.1, NF EN 14411, NF EN 12004, classement UPEC",
        lang=lang,
    )

    # ── FIN-02 Menuiserie interieure ──
    _add_fiche(doc,
        code="FIN-02",
        titre="Menuiserie interieure" if lang == 'fr' else "Interior Joinery",
        norme_ref="DTU 36.1 / NF EN 14351-2",
        specs=[
            ("Porte isoplane" if lang == 'fr' else "Flush door", "83 x 204 cm, ame alveolee"),
            ("Porte postformee" if lang == 'fr' else "Post-formed door", "83 x 204 cm, stratifie"),
            ("Porte CF (coupe-feu)" if lang == 'fr' else "Fire door", "EI 30 ou EI 60"),
            ("Bloc-porte" if lang == 'fr' else "Door set", "Huisserie bois ou metal"),
            ("Quincaillerie" if lang == 'fr' else "Hardware", "Poignee + serrure + paumelles"),
            ("Epaisseur vantail" if lang == 'fr' else "Leaf thickness", "40 mm (standard), 54 mm (CF)"),
            ("Passage libre" if lang == 'fr' else "Clear opening", "83 cm (standard), 90 cm (PMR)"),
        ],
        meo_items=[
            "Pose apres enduits et avant peinture" if lang == 'fr' else "Install after renders, before painting",
            "Huisserie: scellement au mortier ou chevilles mecaniques" if lang == 'fr' else "Frame: mortar fixing or mechanical anchors",
            "Jeu peripherique 3-5 mm pour dilatation" if lang == 'fr' else "3-5 mm peripheral gap for expansion",
            "Quincaillerie PMR: poignee a 1.05 m, bequille" if lang == 'fr' else "Accessible hardware: handle at 1.05 m, lever type",
            "Equipe: 1 menuisier + 1 aide / 4-6 portes/jour" if lang == 'fr' else "Crew: 1 joiner + 1 helper / 4-6 doors/day",
        ],
        fournisseurs="Menuiseries locales Dakar, CFAO Materials, Sogequip, Huet (import)",
        normes="DTU 36.1, NF EN 14351-2, NF P 23-305 (portes CF)",
        lang=lang,
    )

    # ── FIN-03 Menuiserie exterieure ──
    _add_fiche(doc,
        code="FIN-03",
        titre="Menuiserie exterieure (aluminium)" if lang == 'fr' else "Exterior Joinery (aluminium)",
        norme_ref="DTU 36.5 / NF EN 14351-1",
        specs=[
            ("Profil alu" if lang == 'fr' else "Alu profile", "Rupture de pont thermique (RPT)"),
            ("Vitrage" if lang == 'fr' else "Glazing", "4/16/4 double, Ug <= 1.1 W/m2K"),
            ("Vitrage securite" if lang == 'fr' else "Safety glazing", "44.2 feuillete (RdC, garde-corps)"),
            ("Etancheite air/eau/vent" if lang == 'fr' else "AEV rating", "A*3 / E*6A / V*A3"),
            ("Coulissant" if lang == 'fr' else "Sliding", "2-3 vantaux rail alu"),
            ("Ouvrant a la francaise" if lang == 'fr' else "Casement", "1-2 vantaux + oscillo-battant"),
            ("Volet roulant" if lang == 'fr' else "Roller shutter", "Alu thermo-laque + motorise"),
        ],
        meo_items=[
            "Prises de cotes apres gros oeuvre termine" if lang == 'fr' else "Measurements after structural frame complete",
            "Pose en applique ou en feuillure selon type de mur" if lang == 'fr' else "Surface or rebate mounting depending on wall type",
            "Calfeutrement mousse PU + mastic silicone exterieur" if lang == 'fr' else "PU foam sealing + exterior silicone mastic",
            "Bavette alu en traverse basse (rejet d'eau)" if lang == 'fr' else "Aluminium drip bar at bottom rail (water shed)",
            "Equipe: 1 poseur alu + 1 aide / 4-6 m2/jour" if lang == 'fr' else "Crew: 1 alu fitter + 1 helper / 4-6 m2/day",
            "Reception: test d'etancheite au jet d'eau" if lang == 'fr' else "Acceptance: water spray tightness test",
        ],
        fournisseurs="Technal, Schuco, Reynaers, ateliers alu locaux Dakar, K-Line",
        normes="DTU 36.5, NF EN 14351-1, classement AEV, DTU 39 (vitrerie)",
        lang=lang,
    )

    # ── FIN-04 Faux-plafonds ──
    _add_fiche(doc,
        code="FIN-04",
        titre="Faux-plafonds" if lang == 'fr' else "Suspended Ceilings",
        norme_ref="DTU 25.232 (BA13) / NF EN 13964 (ossature)",
        specs=[
            ("BA13 standard" if lang == 'fr' else "Standard plasterboard", "12.5 mm, bord aminci"),
            ("BA13 hydrofuge" if lang == 'fr' else "Moisture-resistant", "H1, pour SDB/cuisine"),
            ("Dalles minerales" if lang == 'fr' else "Mineral tiles", "600x600 mm, ep. 15-19 mm"),
            ("Ossature" if lang == 'fr' else "Grid", "T24 ou T15, porteurs + entretien"),
            ("Plenum" if lang == 'fr' else "Plenum", "15-50 cm selon installations"),
            ("Acoustique NR" if lang == 'fr' else "Acoustic NR", "NRC 0.55-0.70 (dalles minerales)"),
            ("Reaction au feu" if lang == 'fr' else "Fire reaction", "A2-s1,d0 (M0)"),
        ],
        meo_items=[
            "Suspentes tous les 1.20 m max, fixees dans la dalle" if lang == 'fr' else "Hangers every 1.20 m max, fixed to slab",
            "Verification horizontalite au laser rotatif" if lang == 'fr' else "Check level with rotary laser",
            "Joints BA13: bande + 3 passes d'enduit (lissage)" if lang == 'fr' else "Plasterboard joints: tape + 3 coats of filler",
            "Coordination MEP: percements luminaires, bouches VMC, detecteurs" if lang == 'fr' else "MEP coordination: luminaire cutouts, vent grilles, detectors",
            "Equipe: 1 plaquiste + 1 aide / 15-25 m2/jour" if lang == 'fr' else "Crew: 1 dryliner + 1 helper / 15-25 m2/day",
        ],
        fournisseurs="Placoplatre (Saint-Gobain), Knauf, Armstrong (dalles), OWA",
        normes="DTU 25.232, NF EN 520 (BA13), NF EN 13964, NF EN 13501-1 (feu)",
        lang=lang,
    )

    # ── FIN-05 Peinture ──
    _add_fiche(doc,
        code="FIN-05",
        titre="Peinture" if lang == 'fr' else "Painting",
        norme_ref="DTU 59.1 / NF EN 13300",
        specs=[
            ("Acrylique mate" if lang == 'fr' else "Matt acrylic", "Interieur, 2 couches"),
            ("Acrylique satinee" if lang == 'fr' else "Satin acrylic", "SDB, cuisine, couloirs"),
            ("Glycero brillante" if lang == 'fr' else "Gloss alkyd", "Huisseries, boiseries"),
            ("Peinture facade" if lang == 'fr' else "Facade paint", "Pliolite / siloxane"),
            ("Impression" if lang == 'fr' else "Primer", "1 couche fixateur / impression"),
            ("Rendement" if lang == 'fr' else "Coverage", "8-12 m2/L selon support"),
            ("COV" if lang == 'fr' else "VOC", "< 30 g/L (label A+)"),
        ],
        meo_items=[
            "Support sec, propre, depousiere; reboucher fissures" if lang == 'fr' else "Dry, clean, dust-free substrate; fill cracks",
            "Impression obligatoire sur supports neufs" if lang == 'fr' else "Primer mandatory on new substrates",
            "2 couches minimum, croisees (vertical puis horizontal)" if lang == 'fr' else "Minimum 2 coats, cross-applied",
            "Temperature 10-35 C, pas de peinture en plein soleil" if lang == 'fr' else "Temperature 10-35 C, no painting in direct sunlight",
            "Equipe: 1 peintre / 25-40 m2/jour (2 couches)" if lang == 'fr' else "Crew: 1 painter / 25-40 m2/day (2 coats)",
            "Reception: aspect uniforme, pas de coulures ni manques" if lang == 'fr' else "Acceptance: uniform finish, no runs or misses",
        ],
        fournisseurs="Seigneurie/PPG, Tollens/Cromology, SIKA, Colorine, peintures locales",
        normes="DTU 59.1, NF EN 13300, NF T 36-005, label A+",
        lang=lang,
    )

    # ── FIN-06 Cuisine ──
    _add_fiche(doc,
        code="FIN-06",
        titre="Cuisine (meubles et equipements)" if lang == 'fr' else "Kitchen (cabinets and equipment)",
        norme_ref="NF EN 1116 / DTU 60.1 (plomberie)",
        specs=[
            ("Meuble bas" if lang == 'fr' else "Base unit", "Melamine 16-18 mm, L 60-120 cm"),
            ("Meuble haut" if lang == 'fr' else "Wall unit", "H 70 cm, P 35 cm"),
            ("Plan de travail" if lang == 'fr' else "Countertop", "Stratifie HPL ep. 38 mm / granit"),
            ("Evier" if lang == 'fr' else "Sink", "Inox 1 ou 2 bacs, avec egouttoir"),
            ("Robinetterie" if lang == 'fr' else "Faucet", "Mitigeur col de cygne"),
            ("Prise cuisine" if lang == 'fr' else "Kitchen outlet", "4 prises min (NF C 15-100)"),
            ("Ventilation" if lang == 'fr' else "Ventilation", "Hotte aspirante 600-900 mm"),
        ],
        meo_items=[
            "Pose apres carrelage sol/mur et peinture termines" if lang == 'fr' else "Install after floor/wall tiling and painting complete",
            "Meuble bas: reglage pieds pour horizontalite" if lang == 'fr' else "Base units: adjustable feet for level",
            "Meuble haut: fixation par rail metallique + chevilles 8 mm" if lang == 'fr' else "Wall units: metal rail fixing + 8 mm anchors",
            "Plomberie: raccordement evier + lave-vaisselle (siphon double)" if lang == 'fr' else "Plumbing: sink + dishwasher connection (double trap)",
            "Electricite: circuit dedie 32A pour plaque, 20A pour four" if lang == 'fr' else "Electrical: dedicated 32A for hob, 20A for oven",
            "Equipe: 1 cuisiniste + 1 plombier / 1-2 jours par cuisine" if lang == 'fr' else "Crew: 1 kitchen fitter + 1 plumber / 1-2 days per kitchen",
        ],
        fournisseurs="IKEA (import), menuiseries locales, Schmidt, Cuisinella, ateliers Dakar",
        normes="NF EN 1116, NF C 15-100 (electricite cuisine), DTU 60.1",
        lang=lang,
    )

    # ── FOOTER (on last page, before the page break from last fiche) ──
    # Remove the last page break and add footer instead
    # The last _add_fiche added a page break, so we add footer to current page
    footer_p = doc.add_paragraph(f'{_t("generated_by", lang)}')
    footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in footer_p.runs:
        run.font.size = Pt(8)
        run.font.italic = True
        run.font.color.rgb = GRIS
        run.font.name = 'Calibri'

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
