"""
gen_dao.py — Dossier d'Appel d'Offres (DAO) Tijan AI
═══════════════════════════════════════════════════════
Generates tender documents per macro-lot:
  - LOT STRUCTURE (gros oeuvre)
  - LOT MEP (corps d'etat techniques)
  - LOT FINITIONS

Each DAO contains:
  1. BOQ with material/labor cost split
  2. CCTP (Cahier des Clauses Techniques Particulieres)
  3. Recap table

Author: Tijan AI
Version: 1.0 — May 2026
"""

import io
import math
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Table, Spacer, PageBreak, KeepTogether,
    HRFlowable,
)
from tijan_theme import *


# ══════════════════════════════════════════════════════════════
# COST SPLIT RATIOS (fourniture vs pose)
# ══════════════════════════════════════════════════════════════
RATIO_FOURNITURE = {
    "beton":        0.75,
    "acier":        0.60,
    "coffrage":     0.30,
    "terrassement": 0.35,
    "fondations":   0.55,
    "maconnerie":   0.50,
    "etancheite":   0.60,
    "mep":          0.70,
    "finitions":    0.55,
    "installation": 0.40,
    "divers":       0.50,
}


def _ratio_f(cat: str) -> float:
    return RATIO_FOURNITURE.get(cat, 0.50)


def _ratio_p(cat: str) -> float:
    return 1.0 - _ratio_f(cat)


# ══════════════════════════════════════════════════════════════
# I18N — French / English labels
# ══════════════════════════════════════════════════════════════
_T = {
    "fr": {
        "dao_title":        "DOSSIER D'APPEL D'OFFRES",
        "lot_structure":    "LOT STRUCTURE — GROS OEUVRE",
        "lot_mep":          "LOT MEP — CORPS D'ÉTAT TECHNIQUES",
        "lot_finitions":    "LOT FINITIONS — SECOND OEUVRE",
        "section_boq":      "BORDEREAU DES QUANTITÉS ET DES PRIX",
        "section_cctp":     "CAHIER DES CLAUSES TECHNIQUES PARTICULIÈRES",
        "section_recap":    "RÉCAPITULATIF DES PRIX",
        "col_no":           "N°",
        "col_desig":        "Désignation",
        "col_qty":          "Qté",
        "col_unit":         "Unité",
        "col_fourniture":   "Fourniture",
        "col_pose":         "Pose",
        "col_total":        "Total",
        "col_obs":          "Observations",
        "sous_total":       "SOUS-TOTAL",
        "total_general":    "TOTAL GÉNÉRAL",
        "total_fourniture": "Total Fourniture",
        "total_pose":       "Total Pose",
        "generated_by":     "Document généré par Tijan AI — Bureau d'études automatisé",
        "project":          "Projet",
        "location":         "Localisation",
        "building_type":    "Type de bâtiment",
        "surface":          "Surface bâtie",
        "levels":           "Niveaux",
        "date":             "Date",
        "objet":            "Objet et localisation",
        "prescriptions":    "Prescriptions techniques",
        "normes":           "Normes de référence",
        "execution":        "Conditions d'exécution",
        "controles":        "Contrôles et essais",
        "article":          "Article",
        "lot":              "Lot",
        "montant":          "Montant",
        "pct":              "% Total",
    },
    "en": {
        "dao_title":        "TENDER DOCUMENT PACKAGE",
        "lot_structure":    "STRUCTURAL LOT — MAIN WORKS",
        "lot_mep":          "MEP LOT — TECHNICAL TRADES",
        "lot_finitions":    "FINISHES LOT — SECONDARY WORKS",
        "section_boq":      "BILL OF QUANTITIES AND PRICES",
        "section_cctp":     "TECHNICAL SPECIFICATIONS",
        "section_recap":    "PRICE SUMMARY",
        "col_no":           "No.",
        "col_desig":        "Description",
        "col_qty":          "Qty",
        "col_unit":         "Unit",
        "col_fourniture":   "Materials",
        "col_pose":         "Labor",
        "col_total":        "Total",
        "col_obs":          "Notes",
        "sous_total":       "SUB-TOTAL",
        "total_general":    "GRAND TOTAL",
        "total_fourniture": "Total Materials",
        "total_pose":       "Total Labor",
        "generated_by":     "Document generated by Tijan AI — Automated Engineering Bureau",
        "project":          "Project",
        "location":         "Location",
        "building_type":    "Building type",
        "surface":          "Built area",
        "levels":           "Levels",
        "date":             "Date",
        "objet":            "Purpose and location",
        "prescriptions":    "Technical requirements",
        "normes":           "Reference standards",
        "execution":        "Execution conditions",
        "controles":        "Tests and inspections",
        "article":          "Article",
        "lot":              "Lot",
        "montant":          "Amount",
        "pct":              "% Total",
    },
}


def _t(key: str, lang: str = "fr") -> str:
    return _T.get(lang, _T["fr"]).get(key, key)


# ══════════════════════════════════════════════════════════════
# LOT NAME HELPERS
# ══════════════════════════════════════════════════════════════
_LOT_NAMES = {
    "structure":  {"fr": "LOT STRUCTURE — GROS OEUVRE",
                   "en": "STRUCTURAL LOT — MAIN WORKS"},
    "mep":        {"fr": "LOT MEP — CORPS D'ÉTAT TECHNIQUES",
                   "en": "MEP LOT — TECHNICAL TRADES"},
    "finitions":  {"fr": "LOT FINITIONS — SECOND OEUVRE",
                   "en": "FINISHES LOT — SECONDARY WORKS"},
}

_LOT_DOC_TYPE = {
    "structure": "DAO Structure",
    "mep":       "DAO MEP",
    "finitions": "DAO Finitions",
}

_USAGE_LABELS = {
    "residentiel": {"fr": "Résidentiel", "en": "Residential"},
    "bureau":      {"fr": "Bureau",      "en": "Office"},
    "hotel":       {"fr": "Hôtel",       "en": "Hotel"},
    "mixte":       {"fr": "Mixte",       "en": "Mixed-use"},
    "commercial":  {"fr": "Commercial",  "en": "Commercial"},
    "industriel":  {"fr": "Industriel",  "en": "Industrial"},
}


# ══════════════════════════════════════════════════════════════
# TABLE HELPERS
# ══════════════════════════════════════════════════════════════

# 8 columns: N° | Designation | Qty | Unit | Fourniture | Pose | Total | Obs
_COL_W = [0.04, 0.30, 0.06, 0.05, 0.14, 0.14, 0.14, 0.13]


def _col_widths():
    return [CW * w for w in _COL_W]


def _headers(lang="fr"):
    dl = devise_label()
    return [
        p(_t("col_no", lang), "th"),
        p(_t("col_desig", lang), "th"),
        p(_t("col_qty", lang), "th"),
        p(_t("col_unit", lang), "th"),
        p(f'{_t("col_fourniture", lang)} ({dl})', "th"),
        p(f'{_t("col_pose", lang)} ({dl})', "th"),
        p(f'{_t("col_total", lang)} ({dl})', "th"),
        p(_t("col_obs", lang), "th"),
    ]


def _row(no, desig, qty, unite, fourniture, pose, total, obs="",
         bold=False, green=False):
    st = "td_b" if bold else "td"
    st_r = "td_b_r" if bold else "td_r"
    st_t = "td_g_r" if green else st_r
    return [
        p(no, st),
        p(desig, st),
        p(str(qty) if qty != "" else "—", st_r),
        p(unite, st),
        p(fmt_fcfa(fourniture) if fourniture else "—", st_r),
        p(fmt_fcfa(pose) if pose else "—", st_r),
        p(fmt_fcfa(total) if total else "—", st_t),
        p(obs, "small"),
    ]


def _sous_total_row(desig, fourniture, pose, total, lang="fr"):
    return [
        p("", "td_b"), p(f'{_t("sous_total", lang)} — {desig}', "td_b"),
        p("", "td_b"), p("", "td_b"),
        p(fmt_fcfa(fourniture), "td_b_r"),
        p(fmt_fcfa(pose), "td_b_r"),
        p(fmt_fcfa(total), "td_g_r"),
        p("", "td_b"),
    ]


def _split(total_fp, cat):
    """Split a fourni-pose total into (fourniture, pose)."""
    f = int(total_fp * _ratio_f(cat))
    return f, total_fp - f


def _make_table(rows, lang="fr"):
    t = Table([_headers(lang)] + rows, colWidths=_col_widths(), repeatRows=1)
    t.setStyle(table_style())
    return t


# ══════════════════════════════════════════════════════════════
# CCTP HELPER — structured article rendering
# ══════════════════════════════════════════════════════════════

def _cctp_article(story, num, titre, sections, lang="fr"):
    """
    Render a CCTP article with sub-sections.
    sections: list of (subtitle_key, text) tuples
    """
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph(
        f'<b>{_t("article", lang)} {num} — {titre}</b>', S["h2"]))
    story.append(Spacer(1, 1 * mm))
    for subtitle_key, text in sections:
        story.append(Paragraph(
            f'<b>{_t(subtitle_key, lang)}</b>', S["body"]))
        story.append(Paragraph(text, S["body_j"]))
        story.append(Spacer(1, 1 * mm))
    story.append(Spacer(1, 2 * mm))


# ══════════════════════════════════════════════════════════════
# COVER PAGE
# ══════════════════════════════════════════════════════════════

def _cover_page(story, rs_structure, params, lot, lang):
    d = rs_structure.params if rs_structure else None
    nom = params.get("nom", getattr(d, "nom", "Projet Tijan") if d else "Projet Tijan")
    ville = params.get("ville", getattr(d, "ville", "Dakar") if d else "Dakar")
    pays = params.get("pays", getattr(d, "pays", "Senegal") if d else "Senegal")
    usage_raw = params.get("usage", getattr(d, "usage", "residentiel") if d else "residentiel")
    usage_val = usage_raw.value if hasattr(usage_raw, "value") else str(usage_raw)
    usage_label = _USAGE_LABELS.get(usage_val, {}).get(lang, usage_val.capitalize())
    nb_niveaux = params.get("nb_niveaux", getattr(d, "nb_niveaux", 5) if d else 5)
    surface = params.get("surface_emprise_m2",
                         getattr(d, "surface_emprise_m2", 500) if d else 500)
    surf_batie = surface * nb_niveaux

    lot_name = _LOT_NAMES.get(lot, _LOT_NAMES["structure"]).get(lang, lot)

    story.append(Spacer(1, 35 * mm))
    story.append(Paragraph(nom, S["titre"]))
    story.append(Spacer(1, 8 * mm))
    story.append(Paragraph(_t("dao_title", lang), S["h1"]))
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph(lot_name, S["h1"]))
    story.append(Spacer(1, 12 * mm))

    info = [
        [p(f'<b>{_t("location", lang)} :</b> {ville}, {pays}', "body")],
        [p(f'<b>{_t("building_type", lang)} :</b> {usage_label}', "body")],
        [p(f'<b>{_t("surface", lang)} :</b> {fmt_n(surf_batie, 0)} m²'
           f' (emprise {fmt_n(surface, 0)} m²)', "body")],
        [p(f'<b>{_t("levels", lang)} :</b> R+{nb_niveaux - 1}'
           f' ({nb_niveaux} niveaux)', "body")],
        [p(f'<b>{_t("date", lang)} :</b> {datetime.now().strftime("%d/%m/%Y")}',
           "body")],
    ]
    t_info = Table(info, colWidths=[CW])
    t_info.setStyle(TableStyle([
        ("LEFTPADDING",  (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(t_info)

    story.append(Spacer(1, 20 * mm))
    story.append(Paragraph(_t("generated_by", lang), S["small"]))
    story.append(PageBreak())


# ══════════════════════════════════════════════════════════════
# BOQ — LOT STRUCTURE
# ══════════════════════════════════════════════════════════════

def _boq_structure(story, rs, params, lang):
    story += section_title("1", _t("section_boq", lang))
    d = rs.params
    boq = rs.boq
    fond = rs.fondation
    dalle = rs.dalle
    poutre = rs.poutre_principale
    poteaux = rs.poteaux

    try:
        from prix_marche import get_prix_structure
        px = get_prix_structure(d.ville)
    except Exception:
        from prix_marche import get_prix_structure
        px = get_prix_structure("Dakar")

    prix_beton = {
        "C25/30": px.beton_c2530_m3, "C30/37": px.beton_c3037_m3,
        "C35/45": px.beton_c3545_m3,
        "C40/50": getattr(px, "beton_c4050_m3", 240000),
    }.get(rs.classe_beton, px.beton_c3037_m3)

    prix_acier = (px.acier_ha400_kg if rs.classe_acier == "HA400"
                  else px.acier_ha500_kg)

    nb_pot = (d.nb_travees_x + 1) * (d.nb_travees_y + 1)
    ep_dalle_m = dalle.epaisseur_mm / 1000
    surf_batie = boq.surface_batie_m2

    accumulators = {"total_f": 0, "total_p": 0}
    lot_recap = []

    def _lot_section(lot_num, lot_name, items, cat):
        """items: list of (no, desig, qty, unit, total_fp, obs)"""
        rows = []
        lot_f = 0
        lot_p = 0
        for no, desig, qty, unit, total_fp, obs in items:
            f, pose = _split(int(total_fp), cat)
            lot_f += f
            lot_p += pose
            rows.append(_row(no, desig, qty, unit, f, pose, int(total_fp), obs))
        total = lot_f + lot_p
        rows.append(_sous_total_row(lot_name, lot_f, lot_p, total, lang))
        accumulators["total_f"] += lot_f
        accumulators["total_p"] += lot_p
        lot_recap.append((lot_num, lot_name, lot_f, lot_p, total))
        story += section_title(f"1.{lot_num}", lot_name)
        story.append(_make_table(rows, lang))

    # --- Lot 1: Installation ---
    perim = 4 * math.sqrt(d.surface_emprise_m2)
    inst_items = [
        ("1.1", "Cloture de chantier (palissade bois ou tole)",
         int(perim), "ml", int(perim * 15000), ""),
        ("1.2", "Base vie chantier (bureau, vestiaires, sanitaires)",
         1, "fft", int(surf_batie * 800), "Modulaires demontables"),
        ("1.3", "Branchements provisoires eau + electricite",
         1, "fft", int(surf_batie * 500), ""),
        ("1.4", "Signaletique securite + EPI",
         1, "fft", int(surf_batie * 300), ""),
        ("1.5", "Repli et nettoyage fin de chantier",
         1, "fft", int(surf_batie * 600), ""),
    ]
    _lot_section("1", "Installation de chantier", inst_items, "installation")

    # --- Lot 2: Terrassement ---
    V_decap = d.surface_emprise_m2 * 0.30
    V_fouilles = d.surface_emprise_m2 * (fond.profondeur_m + 0.50)
    V_remblai = V_fouilles * 0.30
    V_evacu = V_fouilles * 0.70

    terr_items = [
        ("2.1", "Decapage terre vegetale e=30cm",
         int(V_decap), "m3", int(V_decap * px.terr_mecanique_m3), ""),
        ("2.2", "Fouilles generales mecaniques",
         int(V_fouilles), "m3", int(V_fouilles * px.terr_mecanique_m3),
         "Engins mecaniques"),
        ("2.3", "Fouilles manuelles fond de fouille",
         int(V_fouilles * 0.10), "m3",
         int(V_fouilles * 0.10 * px.terr_manuel_m3), "Finitions"),
        ("2.4", "Remblai compacte (materiaux selectionnes)",
         int(V_remblai), "m3", int(V_remblai * px.remblai_m3), ""),
        ("2.5", "Evacuation terres excedentaires",
         int(V_evacu), "m3", int(V_evacu * 5000), "Transport + decharge"),
        ("2.6", "Lit de sable sous dallage e=10cm",
         int(d.surface_emprise_m2 * 0.10), "m3",
         int(d.surface_emprise_m2 * 0.10 * 12000), ""),
    ]
    _lot_section("2", "Terrassement", terr_items, "terrassement")

    # --- Lot 3: Fondations ---
    fond_items = []
    if fond.nb_pieux > 0:
        prix_pieu = {
            600: px.pieu_fore_d600_ml,
            800: px.pieu_fore_d800_ml,
            1000: px.pieu_fore_d1000_ml,
        }.get(fond.diam_pieu_mm, px.pieu_fore_d800_ml)
        kg_fond = fond.nb_pieux * fond.As_cm2 / 10000 * 7850 * fond.longueur_pieu_m
        c_pieux = int(fond.nb_pieux * fond.longueur_pieu_m * prix_pieu)
        c_longr = int(nb_pot * 6 * 85000)
        fond_items = [
            ("3.1", f"Pieux fores beton arme D{fond.diam_pieu_mm}mm L={fond.longueur_pieu_m}m",
             int(fond.nb_pieux * fond.longueur_pieu_m), "ml", c_pieux,
             f"{fond.nb_pieux} pieux"),
            ("3.2", f"Armatures pieux {rs.classe_acier}",
             int(kg_fond), "kg", int(kg_fond * prix_acier),
             f"As={fond.As_cm2}cm2/pieu"),
            ("3.3", "Beton de proprete e=10cm sous longrines",
             int(nb_pot * 0.5 * 0.5 * 0.10), "m3",
             int(nb_pot * 0.5 * 0.5 * 0.10 * 120000), ""),
            ("3.4", f"Longrines BA {rs.classe_beton} 30x50cm",
             int(nb_pot * 6), "ml", c_longr, "Liaisons pieux"),
            ("3.5", "Tetes de pieux + chapiteaux BA",
             nb_pot, "U", int(nb_pot * 120000), ""),
        ]
    elif fond.beton_semelle_m3 > 0:
        fond_items = [
            ("3.1", "Beton de proprete e=10cm",
             int(d.surface_emprise_m2 * 0.10), "m3",
             int(d.surface_emprise_m2 * 0.10 * 120000), ""),
            ("3.2", f"Semelles beton arme {rs.classe_beton}",
             int(fond.beton_semelle_m3 * 0.6), "m3",
             int(fond.beton_semelle_m3 * 0.6 * prix_beton), ""),
            ("3.3", f"Armatures semelles {rs.classe_acier}",
             int(fond.beton_semelle_m3 * 100), "kg",
             int(fond.beton_semelle_m3 * 100 * prix_acier), ""),
            ("3.4", "Coffrage semelles",
             int(fond.beton_semelle_m3 * 2), "m2",
             int(fond.beton_semelle_m3 * 2 * px.coffrage_bois_m2), ""),
        ]
    _lot_section("3", "Fondations", fond_items, "fondations")

    # --- Lot 4: Structure BA ---
    # Poteaux
    c_pot_total = 0
    pot_items = []
    for i, pt in enumerate(poteaux):
        b = pt.section_mm / 1000
        V_niv = b ** 2 * d.hauteur_etage_m * nb_pot
        As_niv = (pt.nb_barres * math.pi * pt.diametre_mm ** 2 / 400
                  * nb_pot * d.hauteur_etage_m * 7850 / 10000)
        c_beton = int(V_niv * prix_beton)
        c_acier = int(As_niv * prix_acier)
        c_coff = int(4 * b * d.hauteur_etage_m * nb_pot * px.coffrage_bois_m2)
        c_niv = c_beton + c_acier + c_coff
        c_pot_total += c_niv
        pot_items.append((
            f"4.1.{i+1}",
            f"Poteaux {pt.niveau} {pt.section_mm}x{pt.section_mm}mm "
            f"{pt.nb_barres}HA{pt.diametre_mm}",
            nb_pot, "U", c_niv,
            f"NEd={pt.NEd_kN:.0f}kN",
        ))

    # Poutres
    b_p = poutre.b_mm / 1000
    h_p = poutre.h_mm / 1000
    L_px = d.nb_travees_x * d.portee_max_m * (d.nb_travees_y + 1) * d.nb_niveaux
    L_py = d.nb_travees_y * d.portee_min_m * (d.nb_travees_x + 1) * d.nb_niveaux
    V_pout = (L_px + L_py) * b_p * (h_p - ep_dalle_m)
    kg_pout = V_pout * 100
    c_pout_beton = int(V_pout * prix_beton)
    c_pout_acier = int(kg_pout * prix_acier)
    c_pout_coff = int((L_px + L_py) * (b_p + 2 * (h_p - ep_dalle_m))
                      * px.coffrage_bois_m2 * 0.6)
    c_pout_total = c_pout_beton + c_pout_acier + c_pout_coff

    # Dalles
    V_dalles = surf_batie * ep_dalle_m * 0.85
    kg_dalles = V_dalles * 80
    c_dalle_beton = int(V_dalles * prix_beton)
    c_dalle_acier = int(kg_dalles * prix_acier)
    c_dalle_coff = int(surf_batie * 0.85 * px.coffrage_bois_m2)
    c_dalle_total = c_dalle_beton + c_dalle_acier + c_dalle_coff

    # Escaliers
    nb_esc = max(1, int(surf_batie / 1500))
    c_esc = int(nb_esc * d.nb_niveaux * 450000)

    struct_items = pot_items + [
        ("4.2", f"Poutres principales {poutre.b_mm}x{poutre.h_mm}mm",
         int(L_px), "ml", c_pout_beton, f"As={poutre.As_inf_cm2}cm2"),
        ("4.3", f"Poutres secondaires {poutre.b_mm}x{poutre.h_mm}mm",
         int(L_py), "ml", int(c_pout_beton * L_py / max(L_px + L_py, 1)), ""),
        ("4.4", f"Armatures poutres {rs.classe_acier}",
         int(kg_pout), "kg", c_pout_acier,
         f"Etriers HA{poutre.etrier_diam_mm}"),
        ("4.5", "Coffrage poutres",
         int((L_px + L_py) * (b_p + 2 * (h_p - ep_dalle_m)) * 0.6), "m2",
         c_pout_coff, ""),
        ("4.6", f"Beton dalles {rs.classe_beton} e={dalle.epaisseur_mm}mm",
         int(V_dalles), "m3", c_dalle_beton, ""),
        ("4.7", f"Armatures dalles {rs.classe_acier}",
         int(kg_dalles), "kg", c_dalle_acier, "Treillis soude + renforts"),
        ("4.8", "Coffrage dalles",
         int(surf_batie * 0.85), "m2", c_dalle_coff, ""),
        ("4.9", f"Escaliers beton arme {rs.classe_beton}",
         nb_esc * d.nb_niveaux, "volee", 450000 * nb_esc * d.nb_niveaux // max(nb_esc * d.nb_niveaux, 1), c_esc,
         f"{nb_esc} cage(s)"),
    ]
    # Fix escaliers item: total_fp is c_esc
    struct_items[-1] = (
        "4.9", f"Escaliers beton arme {rs.classe_beton}",
        nb_esc * d.nb_niveaux, "volee", c_esc,
        f"{nb_esc} cage(s)",
    )
    _lot_section("4", f"Structure beton arme {rs.classe_beton}/{rs.classe_acier}",
                 struct_items, "beton")

    # --- Lot 5: Maconnerie ---
    cl = rs.cloisons
    opt_rec = next((o for o in cl.options if o.type == cl.option_recommandee),
                   cl.options[0])
    surf_facades = (4 * math.sqrt(d.surface_emprise_m2)
                    * d.nb_niveaux * d.hauteur_etage_m * 0.70)
    surf_enduit = (surf_facades + cl.surface_separative_m2) * 2

    maco_items = [
        ("5.1", "Maconnerie facades ext. agglos pleins 25cm",
         int(surf_facades), "m2",
         int(surf_facades * px.agglo_plein_25_m2), "Enduits 2 faces"),
        ("5.2", f"Cloisons separatives — {opt_rec.materiau[:35]}",
         int(cl.surface_separative_m2), "m2",
         int(cl.surface_separative_m2 * opt_rec.prix_fcfa_m2), ""),
        ("5.3", "Cloisons legeres interieures BA13",
         int(cl.surface_legere_m2), "m2",
         int(cl.surface_legere_m2 * px.ba13_simple_m2), ""),
        ("5.4", "Gaines techniques beton arme 20cm",
         int(cl.surface_gaines_m2), "m2",
         int(cl.surface_gaines_m2 * px.beton_c3037_m3 * 0.20), ""),
        ("5.5", "Enduits ciment + platre int./ext.",
         int(surf_enduit), "m2", int(surf_enduit * 8500), ""),
        ("5.6", "Acroteres beton arme h=60cm",
         int(perim), "ml", int(perim * 35000), ""),
    ]
    _lot_section("5", "Maconnerie et cloisons", maco_items, "maconnerie")

    # --- Lot 6: Etancheite ---
    surf_etanch = d.surface_emprise_m2
    c_salles = int(surf_batie * 0.08 * px.etanch_liquide_m2)
    etanch_items = [
        ("6.1", "Etancheite toiture-terrasse SBS bicouche",
         int(surf_etanch), "m2", int(surf_etanch * px.etanch_sbs_m2),
         "DTU 43.1"),
        ("6.2", "Protection etancheite chape e=5cm",
         int(surf_etanch), "m2", int(surf_etanch * 5000), ""),
        ("6.3", "Etancheite salles de bains",
         int(surf_batie * 0.08), "m2", c_salles, "Resine monocomposant"),
    ]
    if getattr(d, "avec_sous_sol", False):
        etanch_items.append(
            ("6.4", "Etancheite sous-sol membrane PVC",
             int(d.surface_emprise_m2), "m2",
             int(d.surface_emprise_m2 * px.etanch_pvc_m2), "Cuvelage"))
    _lot_section("6", "Etancheite", etanch_items, "etancheite")

    # --- Lot 7: Divers ---
    sous_tot = accumulators["total_f"] + accumulators["total_p"]
    c_impr = int(sous_tot * 0.05)
    c_bet = int(sous_tot * 0.04)
    c_ctrl = int(sous_tot * 0.015)
    divers_items = [
        ("7.1", "Joints de dilatation",
         max(1, int(surf_batie / 500)), "U",
         int(max(1, int(surf_batie / 500)) * 850000), "1 / 500m2"),
        ("7.2", "Reservations et scellements divers",
         1, "fft", int(surf_batie * 800), ""),
        ("7.3", "Imprevus chantier (5%)",
         1, "fft", c_impr, "Aleas"),
        ("7.4", "Honoraires BET structure (4%)",
         1, "fft", c_bet, "Plans + suivi"),
        ("7.5", "Controle technique (1.5%)",
         1, "fft", c_ctrl, "Organisme agree"),
    ]
    _lot_section("7", "Divers et honoraires", divers_items, "divers")

    return lot_recap, accumulators["total_f"], accumulators["total_p"]


# ══════════════════════════════════════════════════════════════
# BOQ — LOT MEP
# ══════════════════════════════════════════════════════════════

def _boq_mep(story, rs_mep, params, lang):
    story += section_title("1", _t("section_boq", lang))
    d = rs_mep.params
    surf_batie = rs_mep.surf_batie_m2
    nb_log = rs_mep.nb_logements

    try:
        from prix_marche import get_prix_mep
        px = get_prix_mep(d.ville)
    except Exception:
        from prix_marche import get_prix_mep
        px = get_prix_mep("Dakar")

    accumulators = {"total_f": 0, "total_p": 0}
    lot_recap = []

    def _lot_section(lot_num, lot_name, items, cat="mep"):
        rows = []
        lot_f = 0
        lot_p = 0
        for no, desig, qty, unit, total_fp, obs in items:
            f, pose = _split(int(total_fp), cat)
            lot_f += f
            lot_p += pose
            rows.append(_row(no, desig, qty, unit, f, pose, int(total_fp), obs))
        total = lot_f + lot_p
        rows.append(_sous_total_row(lot_name, lot_f, lot_p, total, lang))
        accumulators["total_f"] += lot_f
        accumulators["total_p"] += lot_p
        lot_recap.append((lot_num, lot_name, lot_f, lot_p, total))
        story += section_title(f"1.{lot_num}", lot_name)
        story.append(_make_table(rows, lang))

    elec = rs_mep.electrique
    plomb = rs_mep.plomberie
    cvc = rs_mep.cvc
    cf = rs_mep.courants_faibles
    si = rs_mep.securite_incendie
    asc = rs_mep.ascenseurs

    # --- 1. Electricite CF ---
    elec_items = [
        ("1.1", "TGBT complet", 1, "fft", px.tableau_general_bt, ""),
        ("1.2", "Compteurs monophases", nb_log, "U",
         nb_log * px.compteur_monophase, "Par logement"),
        ("1.3", "Cablage cuivre distribution",
         int(surf_batie * 0.8), "ml",
         int(surf_batie * 0.8 * px.canalisation_cuivre_ml), ""),
        ("1.4", "Luminaires LED standard",
         int(surf_batie / 8), "U",
         int(surf_batie / 8 * px.luminaire_led_standard), "1 / 8m2"),
    ]
    if getattr(elec, "puissance_totale_kW", 0) > 100:
        elec_items.append(
            ("1.5", "Groupe electrogene",
             1, "U", px.groupe_electrogene_100kva, "Secours"))
    _lot_section("1", "Electricite courants forts", elec_items)

    # --- 2. Plomberie ---
    plomb_items = [
        ("2.1", "Colonnes montantes acier galva",
         int(d.nb_niveaux * 2), "ml",
         int(d.nb_niveaux * 2 * px.colonne_montante_ml), "2 colonnes"),
        ("2.2", "Tuyauterie PVC DN100 EU/EV",
         int(surf_batie * 0.3), "ml",
         int(surf_batie * 0.3 * px.tuyau_pvc_dn100_ml), ""),
        ("2.3", "WC double chasse 3/6L",
         int(nb_log * 1.5), "U",
         int(nb_log * 1.5 * px.wc_double_chasse), ""),
        ("2.4", "Robinets economiques",
         int(nb_log * 3), "U",
         int(nb_log * 3 * px.robinet_eco), ""),
        ("2.5", "Cuve eau 10000L",
         max(1, int(surf_batie / 3000)), "U",
         max(1, int(surf_batie / 3000)) * px.cuve_eau_10000l, ""),
        ("2.6", "Pompe surpresseur",
         1, "U", px.pompe_surpresseur_3kw, ""),
    ]
    _lot_section("2", "Plomberie sanitaire", plomb_items)

    # --- 3. CVC ---
    nb_splits_1cv = int(surf_batie * 0.4 / 15)
    nb_splits_2cv = int(surf_batie * 0.3 / 25)
    cvc_items = [
        ("3.1", "Splits muraux 1CV (9000 BTU)",
         nb_splits_1cv, "U",
         nb_splits_1cv * px.split_1cv, "Chambres"),
        ("3.2", "Splits muraux 2CV (18000 BTU)",
         nb_splits_2cv, "U",
         nb_splits_2cv * px.split_2cv, "Sejours"),
        ("3.3", "VMC simple flux par logement",
         nb_log, "U",
         nb_log * px.vmc_simple_flux, "Extraction SDB/cuisine"),
    ]
    _lot_section("3", "CVC — Climatisation et ventilation", cvc_items)

    # --- 4. Courants faibles ---
    cf_items = [
        ("4.1", "Cablage reseau RJ45 Cat6",
         int(surf_batie * 0.3), "ml",
         int(surf_batie * 0.3 * px.cablage_rj45_ml), ""),
        ("4.2", "Prises reseau RJ45",
         int(nb_log * 3), "U",
         int(nb_log * 3 * px.prise_rj45), "3 / logement"),
        ("4.3", "Baie serveur 12U",
         max(1, int(surf_batie / 5000)), "U",
         max(1, int(surf_batie / 5000)) * px.baie_serveur_12u, ""),
        ("4.4", "Cameras IP exterieures",
         max(4, int(perim_from_params(params) / 15)), "U",
         max(4, int(perim_from_params(params) / 15)) * px.camera_ip_exterieure,
         "1 / 15ml facade"),
        ("4.5", "Interphone video",
         nb_log, "U", nb_log * px.interphone_video, "Par logement"),
    ]
    _lot_section("4", "Courants faibles", cf_items)

    # --- 5. Securite incendie ---
    si_items = [
        ("5.1", "Detecteurs fumee optiques",
         int(surf_batie / 30), "U",
         int(surf_batie / 30 * px.detecteur_fumee), "1 / 30m2"),
        ("5.2", "Declencheurs manuels",
         d.nb_niveaux * 2, "U",
         d.nb_niveaux * 2 * px.declencheur_manuel, "2 / niveau"),
        ("5.3", "Sirenes + flash",
         d.nb_niveaux, "U",
         d.nb_niveaux * px.sirene_flash, "1 / niveau"),
        ("5.4", "Centrale incendie",
         1, "U", px.centrale_incendie_16zones, ""),
        ("5.5", "Extincteurs CO2 6kg",
         d.nb_niveaux * 2, "U",
         d.nb_niveaux * 2 * px.extincteur_6kg_co2, "2 / niveau"),
        ("5.6", "Extincteurs poudre 9kg",
         d.nb_niveaux * 2, "U",
         d.nb_niveaux * 2 * px.extincteur_9kg_poudre, "2 / niveau"),
        ("5.7", "RIA DN25",
         int(d.nb_niveaux * 15), "ml",
         int(d.nb_niveaux * 15 * px.ria_dn25_ml), "IT 246"),
    ]
    _lot_section("5", "Securite incendie", si_items)

    # --- 6. Ascenseurs ---
    nb_asc = getattr(asc, "nb_ascenseurs", 0) or (1 if d.nb_niveaux >= 4 else 0)
    if nb_asc > 0:
        prix_asc = (px.ascenseur_630kg_r7_r10 if d.nb_niveaux > 6
                    else px.ascenseur_630kg_r4_r6)
        asc_items = [
            ("6.1", f"Ascenseur 630kg {d.nb_niveaux} niveaux",
             nb_asc, "U", nb_asc * prix_asc, "EN 81-20"),
        ]
        _lot_section("6", "Ascenseurs", asc_items)

    return lot_recap, accumulators["total_f"], accumulators["total_p"]


def perim_from_params(params):
    surface = params.get("surface_emprise_m2", 500)
    return 4 * math.sqrt(surface)


# ══════════════════════════════════════════════════════════════
# BOQ — LOT FINITIONS
# ══════════════════════════════════════════════════════════════

def _boq_finitions(story, rs_structure, params, lang):
    story += section_title("1", _t("section_boq", lang))

    d = rs_structure.params if rs_structure else None
    surface_emprise = params.get("surface_emprise_m2",
                                 getattr(d, "surface_emprise_m2", 500) if d else 500)
    nb_niveaux = params.get("nb_niveaux",
                            getattr(d, "nb_niveaux", 5) if d else 5)
    ville = params.get("ville", getattr(d, "ville", "Dakar") if d else "Dakar")
    surf_batie = surface_emprise * nb_niveaux
    perim = 4 * math.sqrt(surface_emprise)
    nb_log = params.get("nb_logements", max(1, int(surf_batie * 0.85 / 80)))

    try:
        from gen_boq_finitions import FINITIONS_DB, calculer_finitions
        fin = calculer_finitions(surface_emprise, nb_niveaux, ville)
    except Exception:
        fin = None

    accumulators = {"total_f": 0, "total_p": 0}
    lot_recap = []

    def _lot_section(lot_num, lot_name, items, cat="finitions"):
        rows = []
        lot_f = 0
        lot_p = 0
        for no, desig, qty, unit, total_fp, obs in items:
            f, pose = _split(int(total_fp), cat)
            lot_f += f
            lot_p += pose
            rows.append(_row(no, desig, qty, unit, f, pose, int(total_fp), obs))
        total = lot_f + lot_p
        rows.append(_sous_total_row(lot_name, lot_f, lot_p, total, lang))
        accumulators["total_f"] += lot_f
        accumulators["total_p"] += lot_p
        lot_recap.append((lot_num, lot_name, lot_f, lot_p, total))
        story += section_title(f"1.{lot_num}", lot_name)
        story.append(_make_table(rows, lang))

    # Use high_end prices for DAO (middle option)
    v = ville if ville in ["Dakar", "Abidjan", "Casablanca", "Lagos"] else "Dakar"
    try:
        from gen_boq_finitions import FINITIONS_DB as DB
    except Exception:
        DB = {}

    def _prix(poste, tier, key, default):
        try:
            return DB[poste][tier][key].get(v, DB[poste][tier][key].get("default", default))
        except Exception:
            return default

    # --- 1. Carrelage ---
    surf_carrelage = int(surf_batie * 1.0)
    prix_carr = _prix("carrelage", "high_end", "prix_m2", 45000)
    _lot_section("1", "Carrelage et revetements de sol", [
        ("1.1", "Gres cerame importe 60x60 pose incluse",
         surf_carrelage, "m2", surf_carrelage * prix_carr,
         "Porcelanosa / RAK"),
    ])

    # --- 2. Menuiserie interieure ---
    nb_portes = int(surf_batie / 100 * 4.5)
    prix_porte = _prix("menuiserie_interieure", "high_end", "prix_porte", 180000)
    _lot_section("2", "Menuiserie interieure", [
        ("2.1", "Portes bois massif prepeint + huisseries alu",
         nb_portes, "U", nb_portes * prix_porte, ""),
    ])

    # --- 3. Menuiserie exterieure ---
    surf_vitrages = int(perim * nb_niveaux * 3.0 * 0.18)
    prix_fen = _prix("menuiserie_exterieure", "high_end", "prix_m2", 185000)
    _lot_section("3", "Menuiserie exterieure", [
        ("3.1", "Fenetres aluminium thermolaque double vitrage",
         surf_vitrages, "m2", surf_vitrages * prix_fen, "Schuco / Reynaers"),
    ])

    # --- 4. Faux-plafonds ---
    surf_fp = int(surf_batie * 0.75)
    prix_fp = _prix("faux_plafond", "high_end", "prix_m2", 48000)
    _lot_section("4", "Faux-plafonds", [
        ("4.1", "Platre staff decoratif + corniche + spots",
         surf_fp, "m2", surf_fp * prix_fp, "Armstrong / Barrisol"),
    ])

    # --- 5. Peinture ---
    surf_peinte = int(surf_batie * (2.8 + 1.0))
    prix_peint = _prix("peinture", "high_end", "prix_m2", 9000)
    _lot_section("5", "Peinture", [
        ("5.1", "Peinture acrylique premium lessivable 3 couches",
         surf_peinte, "m2", surf_peinte * prix_peint, "Tollens / Dulux"),
    ])

    # --- 6. Cuisine ---
    ml_cuisine = int(surf_batie / 100 * 2.5)
    prix_cuisine = _prix("cuisine", "high_end", "prix_ml", 450000)
    _lot_section("6", "Cuisines equipees", [
        ("6.1", "Meubles MDF laque + plan granit + electromenager",
         ml_cuisine, "ml", ml_cuisine * prix_cuisine, "Schmidt / Nobilia"),
    ])

    return lot_recap, accumulators["total_f"], accumulators["total_p"]


# ══════════════════════════════════════════════════════════════
# CCTP — LOT STRUCTURE
# ══════════════════════════════════════════════════════════════

def _cctp_structure(story, rs, params, lang):
    story.append(PageBreak())
    story += section_title("2", _t("section_cctp", lang))

    d = rs.params
    classe_beton = rs.classe_beton
    classe_acier = rs.classe_acier
    fck = rs.fck_MPa
    enrobage = 30 if rs.distance_mer_km > 5 else 40

    # Article 1 — Beton
    dosage = {"C25/30": 350, "C30/37": 400, "C35/45": 420, "C40/50": 450}.get(
        classe_beton, 400)
    _cctp_article(story, 1, "Beton", [
        ("objet", f"Fourniture et mise en oeuvre de beton {classe_beton} pour "
                  f"tous elements porteurs (fondations, poteaux, poutres, dalles, "
                  f"escaliers, voiles). Classe d'exposition XC1/XC2"
                  f"{'/XS1' if rs.distance_mer_km < 5 else ''}."),
        ("prescriptions",
         f"Classe de resistance : {classe_beton} (fck = {fck} MPa). "
         f"Dosage minimum ciment : {dosage} kg/m3. "
         f"Rapport E/C maximum : 0.55. "
         f"Affaissement au cone d'Abrams : classe S3 (100-150 mm). "
         f"Adjuvants : plastifiant reducteur d'eau, retardateur de prise si "
         f"temperature > 30 deg C. "
         f"Granulats : 0/20 mm, propres, non reactifs (norme NF EN 12620). "
         f"Cure : 7 jours minimum par arrosage ou produit de cure NF EN 13670."),
        ("normes",
         "NF EN 206/CN — Beton : specification, performances, production et conformite. "
         "NF EN 12350-2 — Essai affaissement. "
         "NF EN 12390-3 — Resistance en compression. "
         "NF EN 13670 — Execution des structures en beton."),
        ("execution",
         "Beton BPE (Beton Pret a l'Emploi) livre par centrale certifiee. "
         "Mise en oeuvre par pompe ou grue a benne. "
         "Vibration systematique par aiguille vibrante (rayon d'action 40 cm). "
         "Temperature de coulage : 5 deg C < T < 35 deg C. "
         "Reprise de betonnage : piquage + barbotine ciment. "
         "Delai de decoffrage : 24h pour les parois verticales, 21 jours "
         "pour les elements horizontaux (poutres, dalles)."),
        ("controles",
         "Prelevements : 6 eprouvettes par 50 m3 (3 essais a 7 jours, "
         "3 essais a 28 jours). "
         "Resistance caracteristique a 28 jours >= fck. "
         "Essai de consistance au cone : a chaque toupie. "
         "Proces-verbal d'essais par laboratoire agree."),
    ], lang)

    # Article 2 — Aciers
    fyk = rs.fyk_MPa
    _cctp_article(story, 2, "Aciers pour beton arme", [
        ("objet",
         f"Fourniture, faconnage et pose d'armatures en acier {classe_acier} "
         f"pour tous elements de structure."),
        ("prescriptions",
         f"Nuance : {classe_acier} (fyk = {fyk} MPa). "
         f"Haute adherence, soudable. "
         f"Tolerance sur diametres : +/- 4.5% (NF A 35-080). "
         f"Enrobage minimum des armatures : {enrobage} mm "
         f"({'exposition marine' if rs.distance_mer_km < 5 else 'exposition courante'}). "
         f"Faconnage : mandrin de cintrage >= 4 x diametre barre. "
         f"Longueur de recouvrement : 40 x diametre barre minimum."),
        ("normes",
         "NF A 35-080 — Aciers pour beton arme. "
         "NF EN 10080 — Aciers pour l'armature du beton. "
         "Eurocode 2 (NF EN 1992-1-1) — Calcul des structures en beton."),
        ("execution",
         "Stockage : sur cales, a l'abri de l'humidite et des souillures. "
         "Faconnage : a froid, sur gabarit. Interdiction de chauffer les barres. "
         "Ligatures : fil recuit 1.5 mm minimum. "
         "Calage : cales plastiques certifiees pour garantir l'enrobage. "
         "Soudure interdite sans accord du BET."),
        ("controles",
         "Certificat d'origine de l'acier (certificat NF ou equivalent). "
         "Essai de traction : 1 essai par lot de 10 tonnes. "
         "Verification enrobage avant coulage par BET ou controle technique. "
         "Photos avant coulage (piece jointe au PV)."),
    ], lang)

    # Article 3 — Coffrages
    _cctp_article(story, 3, "Coffrages", [
        ("objet",
         "Fourniture, pose et depose de coffrages pour tous elements en "
         "beton arme (poteaux, poutres, dalles, voiles, escaliers)."),
        ("prescriptions",
         "Coffrages bois : contreplaque marine 18 mm minimum. "
         "Coffrages metalliques : autorises pour elements repetitifs. "
         "Planeite des parements : classe A (tolerance 5 mm/2m) pour "
         "parois visibles, classe B pour parois non visibles. "
         "Huile de decoffrage : biodegradable, compatible beton. "
         "Reutilisation maximum : 5 fois pour bois, 50 fois pour metal."),
        ("normes",
         "NF EN 13670 — Execution des structures en beton. "
         "DTU 21 — Execution des ouvrages en beton."),
        ("execution",
         "Verification de l'etancheite avant coulage. "
         "Etaiement : calcul de charge par le coffreur. "
         "Contre-fleche de 1/500eme de la portee pour poutres > 4 m. "
         "Decintrement : 24 h pour poteaux et voiles, 7 jours pour dalles "
         "(si resistance > 70% fck), 21 jours pour poutres de portee > 6 m."),
        ("controles",
         "Verification geometrique avant coulage (cotes, niveaux, aplomb). "
         "Controle de la deformation apres decoffrage. "
         "Fiche de suivi coffrage/decoffrage par element."),
    ], lang)

    # Article 4 — Terrassement
    _cctp_article(story, 4, "Terrassement", [
        ("objet",
         "Decapage, fouilles generales et en rigoles, remblaiement, "
         "evacuation des terres excedentaires."),
        ("prescriptions",
         f"Profondeur de fouille : {rs.fondation.profondeur_m:.1f} m minimum. "
         f"Pression admissible du sol : {rs.pression_sol_MPa} MPa. "
         "Fond de fouille : dress, regle, compact. "
         "Remblai : materiaux selectionnes, 0/31.5 mm, IP < 12. "
         "Compactage : 95% de l'OPM (Optimum Proctor Modifie)."),
        ("normes",
         "DTU 12 — Terrassement. "
         "NF P 94-093 — Essai Proctor. "
         "NF P 94-117 — Essai a la plaque."),
        ("execution",
         "Terrassement mecanique (pelle hydraulique + camion). "
         "Protection des fouilles : blindage si profondeur > 1.30 m. "
         "Pompage des eaux d'infiltration si necessaire. "
         "Remblaiement par couches de 30 cm compactees."),
        ("controles",
         "Essai a la plaque sur fond de fouille (EV2 > 50 MPa). "
         "Essai Proctor sur chaque zone de remblai. "
         "Controle topographique des fonds de fouille. "
         "Proces-verbal du geotechnicien."),
    ], lang)

    # Article 5 — Fondations
    type_fond = rs.fondation.type.value
    _cctp_article(story, 5, "Fondations", [
        ("objet",
         f"Execution des fondations type '{type_fond}'. "
         f"Profondeur d'assise : {rs.fondation.profondeur_m:.1f} m."),
        ("prescriptions",
         f"Type : {type_fond}. "
         f"Beton : {classe_beton} (identique a la superstructure). "
         f"Beton de proprete : C12/15, epaisseur 10 cm minimum. "
         f"Armatures : {classe_acier}, enrobage 50 mm (contact sol). "
         + (f"Pieux : diametre {rs.fondation.diam_pieu_mm} mm, "
            f"longueur {rs.fondation.longueur_pieu_m} m, "
            f"nombre : {rs.fondation.nb_pieux}. "
            if rs.fondation.nb_pieux > 0 else "")),
        ("normes",
         "Eurocode 7 (NF EN 1997-1) — Calcul geotechnique. "
         "DTU 13.2 — Fondations profondes. "
         "NF EN 1536 — Pieux fores (si applicable)."),
        ("execution",
         "Implantation par geometre agree. "
         "Beton de proprete coule avant armatures. "
         + ("Forage par tariere ou bentonite selon terrain. "
            "Cage d'armatures descendue dans le forage. "
            "Betonnage au tube plongeur. "
            if rs.fondation.nb_pieux > 0 else
            "Coffrage des semelles (bois ou perdues). "
            "Armatures posees sur cales d'enrobage. ")
         + "Cure du beton : 7 jours minimum."),
        ("controles",
         ("Essai d'integrite sonique sur 20% des pieux minimum. "
          "Essai de chargement statique sur 2% des pieux (minimum 1). "
          if rs.fondation.nb_pieux > 0 else
          "Controle du fond de fouille par geotechnicien. ")
         + "Verification des armatures avant coulage. "
         "Prelevements beton : 6 eprouvettes par 50 m3."),
    ], lang)

    # Article 6 — Maconnerie
    _cctp_article(story, 6, "Maconnerie et cloisons", [
        ("objet",
         "Execution des murs de facades, cloisons separatives, "
         "cloisons legeres et gaines techniques."),
        ("prescriptions",
         "Facades exterieures : agglos pleins 25 cm, mortier dosage 350 kg/m3. "
         "Cloisons separatives : selon option retenue (agglos 15-20 cm ou BA13 double). "
         "Cloisons legeres : BA13 simple rail 72/48 + laine minerale 45 mm. "
         "Chainages horizontaux : tous les 3 m en hauteur et en tete de mur. "
         "Chainages verticaux : a chaque angle, jonction avec BA, "
         "et tous les 4 m en facade."),
        ("normes",
         "DTU 20.1 — Ouvrages en maconnerie de petits elements. "
         "NF EN 771-3 — Blocs de beton pour maconnerie. "
         "DTU 25.41 — Ouvrages en plaques de parement en platre."),
        ("execution",
         "Pose a joints de mortier horizontaux et verticaux pleins. "
         "Humidification prealable des agglos. "
         "Tolerance d'aplomb : 10 mm par etage. "
         "Liaison maconnerie/BA par harpage ou fers en attente."),
        ("controles",
         "Essai de resistance des agglos : 1 lot par 500 m2. "
         "Verification d'aplomb et de planeite : regle de 2 m. "
         "Controle des chainages avant coulage."),
    ], lang)

    # Article 7 — Etancheite
    _cctp_article(story, 7, "Etancheite", [
        ("objet",
         "Etancheite de la toiture-terrasse, des salles de bains "
         "et du sous-sol (si applicable)."),
        ("prescriptions",
         "Toiture : membrane SBS (bitume elastomere) bicouche, epaisseur "
         "totale >= 6 mm. "
         "Releves : hauteur >= 15 cm au-dessus du niveau fini. "
         "Forme de pente : 1.5% minimum en beton lege. "
         "Protection : chape ciment de 5 cm ou dallettes sur plots. "
         "Salles de bains : systeme d'etancheite liquide (SPEC), "
         "epaisseur seche >= 1 mm, remontees sur murs 20 cm."),
        ("normes",
         "DTU 43.1 — Etancheite des toitures-terrasses avec elements porteurs "
         "en maconnerie. "
         "DTU 43.3 — Etancheite des toitures-terrasses avec elements porteurs "
         "en toles d'acier nervurees. "
         "NF EN 13707 — Feuilles d'etancheite de toiture bitumineuses."),
        ("execution",
         "Support : sec, propre, lisse, avec primaire d'accrochage. "
         "Soudage a la flamme (chalumeau propane). "
         "Recouvrements : 10 cm minimum en longitudinal, 15 cm en transversal. "
         "Raccords evacuations : manchons prefabriques soudes."),
        ("controles",
         "Essai de mise en eau 48 heures sur toiture-terrasse. "
         "Essai d'adherence de la membrane (1 essai par 200 m2). "
         "Verification des releves et points singuliers. "
         "Proces-verbal d'essai d'etancheite signe par l'entreprise et le MO."),
    ], lang)

    # Article 8 — Controle qualite
    _cctp_article(story, 8, "Controle qualite general", [
        ("objet",
         "Ensemble des controles et essais a realiser pendant le chantier "
         "pour garantir la conformite des ouvrages."),
        ("prescriptions",
         "Plan d'Assurance Qualite (PAQ) a soumettre avant demarrage. "
         "Journal de chantier tenu quotidiennement. "
         "Reunions de chantier hebdomadaires avec PV. "
         "Laboratoire d'essais agree par le maitre d'ouvrage."),
        ("normes",
         "NF EN ISO 9001 — Systeme de management de la qualite. "
         "DTU 21 — Execution des ouvrages en beton. "
         "Eurocode 2 — Annexe nationale."),
        ("execution",
         "Essais beton : 6 eprouvettes / 50 m3 (7j + 28j). "
         "Essais acier : certificat NF + 1 traction / 10 tonnes. "
         "Controle compactage : 1 essai plaque / 200 m2 de remblai. "
         "Controle topographique : implantation + niveaux a chaque niveau."),
        ("controles",
         "Tous les PV d'essais transmis au BET sous 48h. "
         "Non-conformites : fiche NC avec action corrective sous 72h. "
         "Reception provisoire : levee de reserves sous 30 jours. "
         "Garantie de parfait achevement : 12 mois. "
         "Garantie decennale : 10 ans sur structure."),
    ], lang)


# ══════════════════════════════════════════════════════════════
# CCTP — LOT MEP
# ══════════════════════════════════════════════════════════════

def _cctp_mep(story, rs_mep, params, lang):
    story.append(PageBreak())
    story += section_title("2", _t("section_cctp", lang))

    d = rs_mep.params
    elec = rs_mep.electrique
    plomb = rs_mep.plomberie
    cvc = rs_mep.cvc
    nb_log = rs_mep.nb_logements

    puissance = getattr(elec, "puissance_totale_kW", 0)

    # Article 1 — Electricite CF
    _cctp_article(story, 1, "Electricite courants forts", [
        ("objet",
         "Alimentation electrique generale, distribution par niveau, "
         "eclairage et prises de courant de l'ensemble du batiment."),
        ("prescriptions",
         f"Puissance installee estimee : {puissance:.0f} kW. "
         f"TGBT : 1 tableau general + {d.nb_niveaux} tableaux divisionnaires. "
         f"Comptage : {nb_log} compteurs individuels. "
         "Cablage : cuivre, section selon NF C 15-100. "
         "Prises de courant : 2P+T 16A, minimum 5 par piece habitable. "
         "Eclairage : LED exclusivement, efficacite > 100 lm/W. "
         "Mise a la terre : resistance < 10 ohms. "
         "Parafoudre : type 2 en tete d'installation."),
        ("normes",
         "NF C 15-100 — Installations electriques basse tension. "
         "NF C 14-100 — Installations de branchement. "
         "NF EN 62305 — Protection foudre."),
        ("execution",
         "Gaines ICTA encastrees ou en faux-plafond. "
         "Boites de derivation accessibles. "
         "Liaisons equipotentielles dans salles de bains. "
         "Identification de chaque circuit au tableau. "
         "Conformite CONSUEL avant mise en service."),
        ("controles",
         "Mesure d'isolement (> 500 kohms sous 500V). "
         "Mesure de terre (< 10 ohms). "
         "Essai de declenchement des differentiels. "
         "Verification de la selectivite des protections. "
         "Attestation CONSUEL."),
    ], lang)

    # Article 2 — Plomberie
    debit = getattr(plomb, "debit_pointe_ls", 0)
    _cctp_article(story, 2, "Plomberie sanitaire", [
        ("objet",
         "Reseaux d'alimentation en eau froide et chaude, evacuations "
         "EU/EV, equipements sanitaires."),
        ("prescriptions",
         f"Debit de pointe : {debit:.1f} L/s. "
         "Alimentation : tube PER ou multicouche, pression d'epreuve 1.5x PN. "
         "Evacuations : PVC NF-ME, DN100 minimum pour WC. "
         "Pente minimale : 1% pour EU, 2% pour EV. "
         "Anti-belier : sur chaque colonne montante. "
         "Clapets anti-retour : sur alimentation generale. "
         "WC : double chasse 3/6L, classe A economie d'eau. "
         "Robinets : mitigeurs a limiteur de debit 6 L/min."),
        ("normes",
         "DTU 60.11 — Regles de calcul des installations de plomberie sanitaire. "
         "DTU 60.1 — Canalisations eau froide et eau chaude. "
         "NF EN 12056 — Reseaux d'evacuation gravitaire a l'interieur des batiments."),
        ("execution",
         "Colonnes montantes en acier galvanise ou cuivre. "
         "Distribution horizontale en PER ou multicouche. "
         "Calorifugeage eau chaude : epaisseur 19 mm minimum. "
         "Traversees planchers/murs : fourreaux PVC avec joint coupe-feu. "
         "Pente des evacuations respectee avec controle au niveau laser."),
        ("controles",
         "Epreuve hydrostatique a 10 bars pendant 30 minutes. "
         "Verification des pentes par niveau laser. "
         "Essai d'ecoulement de chaque appareil. "
         "Controle des siphons et ventilations primaires."),
    ], lang)

    # Article 3 — CVC
    puiss_froid = getattr(cvc, "puissance_frigorifique_kW", 0)
    _cctp_article(story, 3, "CVC — Climatisation et ventilation", [
        ("objet",
         "Climatisation des locaux habitables, ventilation mecanique "
         "controlee des pieces humides."),
        ("prescriptions",
         f"Puissance frigorifique totale : {puiss_froid:.0f} kW. "
         "Splits muraux : type inverter, fluide R32, COP > 3.5. "
         "VMC simple flux : extraction 15 m3/h par SDB, 20 m3/h par cuisine. "
         "Temperature de consigne : 26 deg C (confort tropical). "
         "Filtration : G4 minimum sur chaque unite."),
        ("normes",
         "DTU 68.3 — Installations de ventilation mecanique. "
         "NF EN 14511 — Climatiseurs, groupes refroidisseurs de liquide. "
         "RE 2020 (adaptation Afrique de l'Ouest) — Performance energetique."),
        ("execution",
         "Unites exterieures : sur support antivibratile, acces maintenance. "
         "Liaisons frigorifiques : cuivre deshydrate, brasage sous azote. "
         "Evacuation condensats : PVC DN20 avec siphon et pente 1%. "
         "Gaines VMC : aluminium flexible isole, raccords etanches."),
        ("controles",
         "Essai d'etancheite du circuit frigorifique (azote 30 bars / 24h). "
         "Mesure de debits d'air aux bouches. "
         "Verification de la temperature de soufflage. "
         "Mise en service par technicien agree du fabricant."),
    ], lang)

    # Article 4 — Courants faibles
    _cctp_article(story, 4, "Courants faibles", [
        ("objet",
         "Precablage informatique, videosurveillance, controle d'acces, "
         "interphonie."),
        ("prescriptions",
         "Cablage reseau : RJ45 categorie 6 UTP, longueur max 90 m. "
         "Baie de brassage : 12U minimum, ventilee. "
         "Videosurveillance : cameras IP 2 Mpx minimum, IR 30 m, "
         "enregistreur NVR 30 jours. "
         "Controle d'acces : badge sans contact Mifare, "
         "gache electrique fail-safe. "
         "Interphone : video couleur, deverrouillage a distance."),
        ("normes",
         "NF EN 50173 — Systemes de cablage generique. "
         "NF EN 50174 — Installation de cablage. "
         "NF C 15-100 titre 7 — Installations courants faibles."),
        ("execution",
         "Chemins de cables separes des courants forts (30 cm minimum). "
         "Tubes ICTA dedies courants faibles (couleur verte). "
         "Certification Categorie 6 de chaque lien par testeur Fluke. "
         "Cameras : fixation antivibratile, orientation validee par MO."),
        ("controles",
         "Test de certification Cat 6 de chaque prise (rapport Fluke). "
         "Verification de la couverture camera sur plan. "
         "Test fonctionnel de chaque badge d'acces. "
         "Essai de communication interphone de chaque logement."),
    ], lang)

    # Article 5 — Securite incendie
    _cctp_article(story, 5, "Securite incendie", [
        ("objet",
         "Systeme de securite incendie (SSI), detection, alarme, "
         "moyens de premiere intervention (RIA, extincteurs)."),
        ("prescriptions",
         "SSI categorie A ou B selon classement ERP. "
         "Detection : detecteurs optiques de fumee, 1 par 30 m2. "
         "Declencheurs manuels : 2 par niveau (cage escalier + palier). "
         "RIA DN25 : pression 2.5 bars au robinet le plus defavorise, "
         "portee 20 m (IT 246). "
         "Extincteurs : 1 CO2 6 kg + 1 poudre 9 kg par niveau. "
         "Balisage evacuation : BAES autonomie 1h, NF C 71-800."),
        ("normes",
         "IT 246 — Desenfumage et securite incendie ERP. "
         "NF S 61-970 — SSI de categorie A. "
         "NF S 61-931 — Equipements d'alarme. "
         "NF EN 12845 — Installations fixes de lutte contre l'incendie."),
        ("execution",
         "Detecteurs : fixation au plafond, a 50 cm minimum des murs. "
         "RIA : acier galvanise, peinture anticorrosion, "
         "robinet d'arret a chaque niveau. "
         "Centrale : dans local securite, alimentation secourue 72h. "
         "Report d'alarme : sirenes exterieures + report gardien."),
        ("controles",
         "Essai fumigene de chaque detecteur. "
         "Essai de pression RIA (2.5 bars / 1h). "
         "Verification du fonctionnement de la centrale. "
         "Visite de la commission de securite avant ouverture. "
         "Maintenance : contrat annuel obligatoire."),
    ], lang)

    # Article 6 — Ascenseurs
    nb_asc = getattr(rs_mep.ascenseurs, "nb_ascenseurs", 0)
    if nb_asc > 0 or d.nb_niveaux >= 4:
        _cctp_article(story, 6, "Ascenseurs", [
            ("objet",
             f"Fourniture et installation de {max(nb_asc, 1)} ascenseur(s) "
             f"pour {d.nb_niveaux} niveaux."),
            ("prescriptions",
             "Charge nominale : 630 kg (8 personnes). "
             "Vitesse : 1.0 m/s. "
             "Traction : a adherence, sans local de machines (MRL). "
             "Cabine : dimensions 1100 x 1400 mm, hauteur 2200 mm. "
             "Portes palieres : automatiques telescopiques, inox brossee. "
             "Eclairage cabine : LED, autonomie secours 1h. "
             "Indicateur de position : afficheur LCD a chaque palier."),
            ("normes",
             "EN 81-20 — Regles de securite pour la construction et "
             "l'installation des ascenseurs. "
             "EN 81-50 — Regles de conception, calculs, examens et essais. "
             "NF EN 81-70 — Accessibilite PMR."),
            ("execution",
             "Gaine beton : dimensions selon plans du constructeur. "
             "Cuvette : profondeur minimum 1.2 m, etancheite. "
             "Local technique en terrasse ou au sous-sol. "
             "Alimentation electrique dediee + batterie de secours."),
            ("controles",
             "Epreuves statiques : 125% de la charge nominale. "
             "Epreuves dynamiques : 110% de la charge nominale. "
             "Verification par organisme agree avant mise en service. "
             "Contrat de maintenance obligatoire (type complet). "
             "Visite technique annuelle par organisme agree."),
        ], lang)


# ══════════════════════════════════════════════════════════════
# CCTP — LOT FINITIONS
# ══════════════════════════════════════════════════════════════

def _cctp_finitions(story, rs_structure, params, lang):
    story.append(PageBreak())
    story += section_title("2", _t("section_cctp", lang))

    # Article 1 — Carrelage
    _cctp_article(story, 1, "Carrelage et revetements de sol", [
        ("objet",
         "Fourniture et pose de carrelage dans l'ensemble des locaux "
         "habitables et circulations."),
        ("prescriptions",
         "Type : gres cerame emaille, format 60x60 cm. "
         "Classement UPEC : U3 P3 E2 C1 (logement) / U4 P3 E2 C2 (halls). "
         "Resistance au glissement : R10 minimum (locaux humides R11). "
         "Absorption d'eau : < 0.5% (norme ISO 10545-3). "
         "Joints : 2 mm minimum, coulis ciment ameliore."),
        ("normes",
         "DTU 52.1 — Revetements de sols scelles. "
         "DTU 52.2 — Revetements de sols colles. "
         "NF EN 14411 — Carreaux ceramiques."),
        ("execution",
         "Support : chape de nivellement tiree a la regle, seche (< 5% humidite). "
         "Pose : a la colle C2S1 (deformable) sur peigne crante. "
         "Double encollage pour formats > 45x45 cm. "
         "Joints de fractionnement : tous les 40 m2 ou 8 ml. "
         "Joint peripherique souple : 5 mm minimum."),
        ("controles",
         "Essai de sondage au maillet : pas de son creux. "
         "Verification planeite : tolerance 2 mm sous regle de 2 m. "
         "Verification alignement et largeur des joints."),
    ], lang)

    # Article 2 — Menuiserie interieure
    _cctp_article(story, 2, "Menuiserie interieure", [
        ("objet",
         "Fourniture et pose de portes interieures, huisseries "
         "et quincaillerie."),
        ("prescriptions",
         "Portes : ame pleine MDF, parement bois prepeint. "
         "Dimensions : 204 x 83 cm (standard) / 204 x 93 cm (PMR). "
         "Huisseries : aluminium laque ou metalliques. "
         "Serrure : type bec-de-cane pour pieces courantes, "
         "a condamnation pour SDB/WC. "
         "Quincaillerie : 3 paumelles par porte, "
         "butoir de porte."),
        ("normes",
         "DTU 36.1 — Menuiseries en bois. "
         "NF EN 14351-2 — Portes et fenetres, portes interieures. "
         "NF P 01-005 — Dimensions de coordination."),
        ("execution",
         "Pose sur huisseries scellees ou vissees (chevilles chimiques). "
         "Jeu fonctionnel : 3 mm en peripherie. "
         "Joints d'etancheite sur huisseries SDB. "
         "Reglage des paumelles apres pose de la serrure."),
        ("controles",
         "Verification de l'aplomb et du niveau de chaque porte. "
         "Essai de fonctionnement (ouverture/fermeture sans frottement). "
         "Verification de la serrure et de la quincaillerie."),
    ], lang)

    # Article 3 — Menuiserie exterieure
    _cctp_article(story, 3, "Menuiserie exterieure (fenetres et baies)", [
        ("objet",
         "Fourniture et pose de fenetres, baies vitrees, portes-fenetres "
         "et volets roulants."),
        ("prescriptions",
         "Chassis : aluminium thermolaque, rupture de pont thermique. "
         "Vitrage : double vitrage 4/16/4 mm (argon), Ug <= 1.1 W/m2.K. "
         "Etancheite a l'air : classe A*4 (NF EN 12207). "
         "Permeabilite a l'eau : classe E*7A (NF EN 12208). "
         "Facteur solaire : g <= 0.35 (climat tropical). "
         "Quincaillerie : oscillo-battant, cremone multipoints."),
        ("normes",
         "DTU 36.5 — Mise en oeuvre des fenetres et portes exterieures. "
         "NF EN 14351-1 — Fenetres et portes — Norme de produit. "
         "NF EN 12207/12208/12210 — Performances air, eau, vent."),
        ("execution",
         "Pose en applique interieure ou en tunnel selon configuration. "
         "Calfeutrement : mousse polyurethane + joint silicone exterieur. "
         "Bavette aluminium en allege. "
         "Protection des menuiseries pendant le chantier (film)."),
        ("controles",
         "Essai d'infiltrometrie (sur echantillon ou in situ). "
         "Verification de l'aplomb, du niveau et de l'equerrage. "
         "Essai de manoeuvre de chaque ouvrant."),
    ], lang)

    # Article 4 — Faux-plafonds
    _cctp_article(story, 4, "Faux-plafonds", [
        ("objet",
         "Fourniture et pose de faux-plafonds dans les zones definies "
         "aux plans (logements, circulations, locaux techniques)."),
        ("prescriptions",
         "Type : plaques de platre BA13 sur ossature metallique. "
         "Hauteur libre sous faux-plafond : 2.50 m minimum. "
         "Plenum : 25 cm minimum pour passage reseaux. "
         "Resistance au feu : M1 ou Euroclasse A2-s1,d0. "
         "Acoustique : absorption alpha_w >= 0.50 (locaux collectifs). "
         "Locaux humides : plaques hydrofuges (H1)."),
        ("normes",
         "DTU 58.1 — Plafonds suspendus. "
         "NF EN 13964 — Plafonds suspendus — Exigences et methodes d'essai. "
         "NF EN 520 — Plaques de platre."),
        ("execution",
         "Ossature : profiles T24 sur suspentes reglables. "
         "Entraxe suspentes : 1.20 m maximum. "
         "Joints : bande + enduit a joint, poncage fin. "
         "Trappe de visite : 1 par 30 m2 pour acces maintenance."),
        ("controles",
         "Verification de la planeite : 2 mm sous regle de 2 m. "
         "Verification du niveau general. "
         "Essai de charge (5 daN/m2 en accessoires)."),
    ], lang)

    # Article 5 — Peinture
    _cctp_article(story, 5, "Peinture", [
        ("objet",
         "Preparation des supports et application de peinture sur "
         "l'ensemble des murs, plafonds et boiseries."),
        ("prescriptions",
         "Murs interieurs : peinture acrylique mate lessivable, 3 couches "
         "(1 impression + 2 couches de finition). "
         "Plafonds : peinture acrylique mate, 2 couches. "
         "Locaux humides (SDB, cuisine) : peinture glycero satinee anti-moisissure. "
         "Facades exterieures : peinture minerale siloxane, 2 couches "
         "(apres enduit monocouche)."),
        ("normes",
         "DTU 59.1 — Peinturage. "
         "NF EN 13300 — Peintures et vernis en phase aqueuse. "
         "NF T 30-700 — Classificiation des systemes de peinture."),
        ("execution",
         "Preparation : rebouchage des fissures (enduit de rebouchage), "
         "poncage, depoussierage. "
         "Impression : sous-couche universelle, sechage 24h. "
         "Application : rouleau pour surfaces planes, brosse pour angles. "
         "Temperature d'application : 10-30 deg C, humidite < 80%."),
        ("controles",
         "Verification de l'aspect (uniformite, pas de coulure). "
         "Controle d'epaisseur : 100 microns minimum en film sec. "
         "Essai de lessivabilite (locaux humides). "
         "Verification des raccords et finitions."),
    ], lang)

    # Article 6 — Cuisine
    _cctp_article(story, 6, "Cuisine equipee", [
        ("objet",
         "Fourniture et installation de cuisines equipees "
         "dans chaque logement."),
        ("prescriptions",
         "Meubles bas : caisson MDF 16 mm, facade laquee, "
         "charniere amortie Blum/Hettich. "
         "Meubles hauts : profondeur 35 cm, fixation sur rail. "
         "Plan de travail : granit ou quartz, epaisseur 20 mm, "
         "joint silicone entre mur et plan. "
         "Evier : inox 18/10, 2 bacs + egouttoir. "
         "Robinetterie : mitigeur a douchette, limiteur de debit."),
        ("normes",
         "NF EN 14749 — Meubles de cuisine et de rangement. "
         "NF EN 1116 — Meubles de cuisine — Dimensions. "
         "NF EN 13310 — Eviers de cuisine."),
        ("execution",
         "Pose sur pieds reglables (plinth de 10 cm). "
         "Niveau : tolerance 1 mm sur toute la longueur. "
         "Raccordement plomberie : flexibles inox NF. "
         "Raccordement electrique : prise dediee 20A pour four, "
         "16A pour lave-vaisselle."),
        ("controles",
         "Verification de l'aplomb et du niveau de chaque element. "
         "Essai d'etancheite des raccordements plomberie. "
         "Essai de fonctionnement electromenager. "
         "Verification des portes et tiroirs (ouverture/fermeture)."),
    ], lang)


# ══════════════════════════════════════════════════════════════
# RECAP TABLE
# ══════════════════════════════════════════════════════════════

def _recap(story, lot_recap, total_f, total_p, lang):
    story.append(PageBreak())
    story += section_title("3", _t("section_recap", lang))

    total = total_f + total_p

    recap_hdr = [
        p(_t("lot", lang), "th"),
        p(_t("col_desig", lang), "th"),
        p(_t("col_fourniture", lang), "th"),
        p(_t("col_pose", lang), "th"),
        p(_t("col_total", lang), "th"),
        p(_t("pct", lang), "th"),
    ]

    rows = [recap_hdr]
    for lot_num, lot_name, f, po, tot in lot_recap:
        pct = f"{tot / total * 100:.1f}%" if total > 0 else "—"
        rows.append([
            p(str(lot_num), "td_b"),
            p(lot_name, "td"),
            p(fmt_fcfa(f), "td_r"),
            p(fmt_fcfa(po), "td_r"),
            p(fmt_fcfa(tot), "td_r"),
            p(pct, "td_r"),
        ])

    # Totals row
    rows.append([
        p("", "td_b"),
        p(_t("total_general", lang), "td_b"),
        p(fmt_fcfa(total_f), "td_g_r"),
        p(fmt_fcfa(total_p), "td_g_r"),
        p(fmt_fcfa(total), "td_g_r"),
        p("100%", "td_b"),
    ])

    col_w = [CW * w for w in [0.06, 0.34, 0.18, 0.18, 0.18, 0.06]]
    t = Table(rows, colWidths=col_w, repeatRows=1)
    ts = table_style(zebra=False)
    ts.add("BACKGROUND", (0, -1), (-1, -1), VERT_LIGHT)
    ts.add("FONTNAME",   (0, -1), (-1, -1), "Helvetica-Bold")
    ts.add("LINEABOVE",  (0, -1), (-1, -1), 1.5, VERT)
    t.setStyle(ts)
    story.append(t)

    # Ratio split
    story.append(Spacer(1, 4 * mm))
    if total > 0:
        pct_f = total_f / total * 100
        pct_p = total_p / total * 100
        story.append(Paragraph(
            f"Repartition : Fourniture {pct_f:.0f}% — Pose {pct_p:.0f}%",
            S["body"]))

    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph(
        "* Ce document est une estimation d'avant-projet (precision +/- 15%). "
        "Les prix unitaires sont bases sur les references marche local 2026. "
        "Un metre definitif sur plans d'execution est requis avant consultation.",
        S["disc"]))


# ══════════════════════════════════════════════════════════════
# MAIN ENTRY POINT
# ══════════════════════════════════════════════════════════════

def generer_dao(rs_structure, rs_mep, params: dict,
                lot: str = "structure", lang: str = "fr") -> bytes:
    """
    Generate tender document (DAO) for a specific lot.

    rs_structure: ResultatsStructure from engine_structure_v2 (required for structure/finitions)
    rs_mep: ResultatsMEP from engine_mep_v2 (required for mep)
    params: project params dict
    lot: "structure" | "mep" | "finitions"
    lang: "fr" | "en"

    Returns: PDF bytes
    """
    set_pdf_lang(lang)

    buf = io.BytesIO()

    # Resolve project name for header
    d = rs_structure.params if rs_structure else (rs_mep.params if rs_mep else None)
    nom = params.get("nom", getattr(d, "nom", "Projet Tijan") if d else "Projet Tijan")
    doc_type = _LOT_DOC_TYPE.get(lot, "DAO")

    hf = HeaderFooter(nom, doc_type, lang=lang)
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=ML, rightMargin=MR,
        topMargin=26 * mm, bottomMargin=18 * mm,
    )

    story = []

    # Cover
    _cover_page(story, rs_structure, params, lot, lang)

    # BOQ + CCTP + Recap per lot
    if lot == "structure":
        if rs_structure is None:
            raise ValueError("rs_structure is required for lot 'structure'")
        lot_recap, total_f, total_p = _boq_structure(
            story, rs_structure, params, lang)
        _cctp_structure(story, rs_structure, params, lang)
        _recap(story, lot_recap, total_f, total_p, lang)

    elif lot == "mep":
        if rs_mep is None:
            raise ValueError("rs_mep is required for lot 'mep'")
        lot_recap, total_f, total_p = _boq_mep(
            story, rs_mep, params, lang)
        _cctp_mep(story, rs_mep, params, lang)
        _recap(story, lot_recap, total_f, total_p, lang)

    elif lot == "finitions":
        lot_recap, total_f, total_p = _boq_finitions(
            story, rs_structure, params, lang)
        _cctp_finitions(story, rs_structure, params, lang)
        _recap(story, lot_recap, total_f, total_p, lang)

    else:
        raise ValueError(f"Unknown lot: {lot}. Use 'structure', 'mep', or 'finitions'.")

    doc.build(story, onFirstPage=hf, onLaterPages=hf)
    return buf.getvalue()
