"""
pdf_strings.py — Strings bilingues pour les générateurs PDF Tijan AI
Usage : from pdf_strings import get_strings
        s = get_strings('en')
        s['note_title']  → 'Structural Calculation Note'
"""

STRINGS = {
    'fr': {
        # Titres documents
        'note_structure_title':     'Note de calcul structure',
        'boq_structure_title':      'Bordereau des Quantités et des Prix — Structure',
        'note_mep_title':           'Note de calcul MEP',
        'boq_mep_title':            'BOQ MEP — Détaillé',
        'edge_title':               'Pré-évaluation EDGE',
        'executif_title':           'Rapport de synthèse exécutif',

        # Sous-titres
        'subtitle_structure':       'Calculs indicatifs ±15% — À vérifier par un ingénieur structure habilité.',
        'subtitle_boq':             'Prix unitaires marché local 2026 (fournis-posés). Marge ±15%.',
        'subtitle_mep':             'Document utilisable pour consultation d\'entreprises.',
        'subtitle_edge':            'IFC EDGE Standard v3',
        'subtitle_executif':        'Ce document est destiné au maître d\'ouvrage.',

        # Sections structure
        'project_data':             'DONNÉES DU PROJET',
        'hypotheses':               'HYPOTHÈSES ET NORMES DE CALCUL',
        'columns':                  'DESCENTE DE CHARGES — POTEAUX (EC2/EC8)',
        'beams':                    'DIMENSIONNEMENT POUTRES (EC2)',
        'slab':                     'DIMENSIONNEMENT DALLE (EC2)',
        'partitions':               'CLOISONS ET MAÇONNERIE',
        'foundations':              'ÉTUDE DES FONDATIONS (EC7 + DTU 13.2)',
        'seismic':                  'ANALYSE SISMIQUE (EC8 — NF EN 1998-1)',
        'analysis':                 'ANALYSE ET RECOMMANDATIONS',
        'boq_section':              'BORDEREAU DES QUANTITÉS ET DES PRIX — STRUCTURE',

        # Colonnes tableaux
        'parameter':    'PARAMÈTRE',
        'value':        'VALEUR',
        'justif':       'JUSTIFICATION',
        'lot':          'Lot',
        'designation':  'Désignation',
        'qty':          'Qté',
        'unit':         'Unité',
        'pu':           'P.U. (FCFA)',
        'amount':       'Montant (FCFA)',
        'amount_low':   'Montant bas',
        'amount_high':  'Montant haut',
        'notes':        'Observations',
        'level':        'Niveau',
        'section':      'Section',
        'rebars':       'Armatures',
        'rate':         'Taux arm.',
        'verif':        'Vérif.',

        # Statuts
        'ok':           '✓ OK',
        'nok':          '✗ NOK',
        'compliant':    '✓ Conforme',
        'to_verify':    '⚠ À vérifier',
        'soon':         'Bientôt',

        # MEP sections
        'elec_section': 'BILAN ÉLECTRICITÉ (NF C 15-100)',
        'plumb_section':'BILAN PLOMBERIE (DTU 60.11 — ONAS)',
        'cvc_section':  'BILAN CVC (EN 12831 — ASHRAE 55)',
        'cf_section':   'COURANTS FAIBLES',
        'fire_section': 'SÉCURITÉ INCENDIE (IT 246)',
        'elev_section': 'ASCENSEURS (EN 81-20/50)',
        'auto_section': 'AUTOMATISATION GTB',

        # EDGE
        'edge_scores':  'SYNTHÈSE DES SCORES EDGE',
        'pillar':       'PILIER',
        'score':        'SCORE PROJET',
        'target':       'SEUIL CIBLE',
        'status':       'STATUT',
        'certifiable':  'CERTIFIABLE',
        'not_cert':     'NON CERTIFIABLE',
        'energy':       'Énergie',
        'water':        'Eau',
        'materials':    'Matériaux',
        'action_plan':  'PLAN D\'ACTION — OPTIMISATION VERS CERTIFICATION',
        'pillar1':      'PILIER 1 — ÉNERGIE',
        'pillar2':      'PILIER 2 — EAU',
        'pillar3':      'PILIER 3 — MATÉRIAUX',
        'measure':      'MESURE',
        'gain':         'GAIN (%)',
        'impact':       'IMPACT PRIX',
        'action':       'ACTION',
        'cost':         'COÛT',
        'roi':          'ROI',

        # Rapport exécutif
        'project_sheet':    'FICHE PROJET',
        'global_budget':    'ESTIMATION BUDGÉTAIRE GLOBALE',
        'edge_perf':        'PERFORMANCE ENVIRONNEMENTALE (EDGE IFC)',
        'key_points':       'POINTS CLÉS ET RECOMMANDATIONS',
        'body_of_work':     'CORPS D\'ÉTAT',
        'total':            'TOTAL',
        'total_go':         'TOTAL GROS ŒUVRE',
        'finishes':         'Finitions (estimation)',
        'total_estimate':   'COÛT TOTAL ESTIMÉ',

        # BOQ labels
        'installation':     'INSTALLATION ET ORGANISATION DE CHANTIER',
        'earthworks':       'TERRASSEMENT GÉNÉRAL',
        'foundation_lot':   'FONDATIONS',
        'structure_lot':    'STRUCTURE BÉTON ARMÉ',
        'masonry_lot':      'MAÇONNERIE, CLOISONS ET ENDUITS',
        'waterproof_lot':   'ÉTANCHÉITÉ ET ISOLATION',
        'misc_lot':         'DIVERS, IMPRÉVUS ET HONORAIRES TECHNIQUES',
        'recap':            'RÉCAPITULATIF GÉNÉRAL',
        'sub_total':        'SOUS-TOTAL',
        'grand_total':      'TOTAL ESTIMATIF HT',
        'low_range':        'FOURCHETTE BASSE (-5%)',
        'high_range':       'FOURCHETTE HAUTE (+15%)',

        # BOQ MEP lots
        'lot_elec':     'ÉLECTRICITÉ COURANTS FORTS (NF C 15-100)',
        'lot_plumb':    'PLOMBERIE SANITAIRE (DTU 60.11)',
        'lot_cvc':      'CLIMATISATION, VENTILATION ET CHAUFFAGE (EN 12831)',
        'lot_cf':       'COURANTS FAIBLES — RÉSEAU, VIDÉO, ACCÈS, INTERPHONIE',
        'lot_fire':     'SÉCURITÉ INCENDIE (IT 246 — France/Sénégal)',
        'lot_elev':     'ASCENSEURS ET MONTE-CHARGES (EN 81-20/50)',
        'lot_auto':     'AUTOMATISATION GTB',


        'project':          'Projet',
        'location':         'Localisation',
        'usage_label':      'Usage',
        'levels_label':     'Niveaux',
        'spans':            'Portées',
        'bays':             'Travées',
        'concrete':         'Béton',
        'steel':            'Acier',
        'soil':             'Sol admissible',
        'sea_dist':         'Distance mer',
        'loads':            'Charges G / Q',
        'seismic_zone':     'Zone sismique',
        'rc_label':         'Béton armé',
        'seismic_label':    'Séismique',
        'perm_loads':       'Charges perm. G',
        'var_loads':        'Charges var. Q',
        'elu_combo':        'Combinaison ELU',
        'foundations_label':'Fondations',
        'durability':       'Durabilité',
        'ned':              'NEd (kN)',
        'section_h':        'Section',
        'nb_bars':          'Nb bar.',
        'diam':             'Ø (mm)',
        'stirrup_d':        'Ø cad.',
        'stirrup_s':        'Esp. cad.',
        'ratio':            'ρ (%)',
        'nrd':              'NRd (kN)',
        'ratio_check':      'NEd/NRd',
        'rho_note':         'ρ = taux armature (EC2 : 0.1% ≤ ρ ≤ 4%) | NEd/NRd < 1 requis',
        'b_mm':             'b (mm)',
        'h_mm':             'h (mm)',
        'as_inf':           'As inf (cm²)',
        'as_sup':           'As sup (cm²)',
        'stirrups':         'Étriers',
        'stir_sp':          'Esp. étr.',
        'span_m':           'Portée (m)',
        'defl_check':       'Vérif. flèche',
        'shear_check':      'Effort tranchant',
        'beam_type':        'Poutre',
        'span_label':       'portée',
        'thickness':        'Épaisseur',
        'as_x':             'As x (cm²/ml)',
        'as_y':             'As y (cm²/ml)',
        'rebar_main':       'Armatures sens porteur principal',
        'rebar_sec':        'Armatures sens secondaire',
        'adm_defl':         'Flèche admissible',
        'verif_label':      'Vérification',
        'justif_label':     'Justification',
        'pile_diam':        'Diamètre pieu',
        'drilled':          'Foré à la tarière creuse',
        'pile_length':      'Longueur pieu',
        'bearing_layer':    "Jusqu'à horizon porteur",
        'reinf':            'Armatures',
        'full_cage':        'Cage HA500B pleine longueur',
        'nb_piles_label':   'Nb pieux total',
        'est_geotech':      'Estimé — à confirmer par BET géotechnique',
        'deep_found_note':  'Fondations profondes = poste le plus coûteux après gros œuvre.',
        'found_cost_note':  'Impact prix fondations',
        'accel':            'Accélération ag',
        'nat_annex':        'Annexe nationale',
        'soil_factor':      'Facteur sol S',
        'soil_c':           'Sol type C — EC8 Tableau 3.2',
        'q_factor':         'Coefficient q',
        'period':           'Période T₁',
        'base_force':       'Force de base Fb',
        'dcl_comp':         'Conformité DCL',
        'add_analysis':     '⚠ Analyse complémentaire',
        'eng_note_label':   'Note de synthèse :',
        'strengths_label':  '✅ Points forts',
        'attention_label':  "⚠ Points d'attention",
        'rec_label':        'Recommandations :',
        'earthworks_item':  'Terrassement — décapage + fouilles méca.',
        'found_item':       'Fondations — pieux/semelles/radier béton armé',
        'masonry_item':     'Maçonnerie — agglos 15cm enduits 2 faces',
        'misc_item':        'Divers — joints, acrotères, réservations',
        'total_struct':     'TOTAL STRUCTURE',
        'low_val':          'VALEUR BASSE',
        'high_val':         'VALEUR HAUTE',
        'total_built':      'Surface bâtie totale',
        'cost_m2_built':    'Coût / m² bâti',
        'cost_m2_hab':      'Coût / m² habitable',
        'total_cost_struct':'COÛT TOTAL STRUCTURE',
        'struct_only':      'Structure seule — hors MEP, finitions, VRD',
        'hab_note':         'Surface habitable ≈ 78% surface bâtie',
        'estimate_note_short': 'Estimation ±15%',
        'grid':             'grille',
        'elu_comb':         'Combinaison ELU :',
        'footing_width':    'Largeur semelle',
        'square_sec':       'Section carrée',
        'depth':            'Profondeur',
        'below_frost':      'Hors gel + horizon porteur',

        'project':          'Projet',
        'location':         'Localisation',
        'usage_label':      'Usage',
        'levels_label':     'Niveaux',
        'built_surface':    'Surface bâtie',
        'hab_surface':      'Surface habitable',
        'spans':            'Portées',
        'bays':             'Travées',
        'concrete':         'Béton',
        'steel':            'Acier',
        'soil':             'Sol admissible',
        'sea_dist':         'Distance mer',
        'loads':            'Charges G / Q',
        'seismic_zone':     'Zone sismique',
        'rc_label':         'Béton armé',
        'seismic_label':    'Séismique',
        'perm_loads':       'Charges perm. G',
        'var_loads':        'Charges var. Q',
        'elu_combo':        'Combinaison ELU',
        'foundations_label':'Fondations',
        'durability':       'Durabilité',
        'ned':              'NEd (kN)',
        'section_h':        'Section',
        'nb_bars':          'Nb bar.',
        'diam':             'Ø (mm)',
        'stirrup_d':        'Ø cad.',
        'stirrup_s':        'Esp. cad.',
        'ratio':            'ρ (%)',
        'nrd':              'NRd (kN)',
        'ratio_check':      'NEd/NRd',
        'rho_note':         'ρ = taux armature (EC2 : 0.1% ≤ ρ ≤ 4%) | NEd/NRd < 1 requis',
        'b_mm':             'b (mm)',
        'h_mm':             'h (mm)',
        'as_inf':           'As inf (cm²)',
        'as_sup':           'As sup (cm²)',
        'stirrups':         'Étriers',
        'stir_sp':          'Esp. étr.',
        'span_m':           'Portée (m)',
        'defl_check':       'Vérif. flèche',
        'shear_check':      'Effort tranchant',
        'beam_type':        'Poutre',
        'span_label':       'portée',
        'thickness':        'Épaisseur',
        'as_x':             'As x (cm²/ml)',
        'as_y':             'As y (cm²/ml)',
        'rebar_main':       'Armatures sens porteur principal',
        'rebar_sec':        'Armatures sens secondaire',
        'adm_defl':         'Flèche admissible',
        'verif_label':      'Vérification',
        'justif_label':     'Justification',
        'pile_diam':        'Diamètre pieu',
        'drilled':          'Foré à la tarière creuse',
        'pile_length':      'Longueur pieu',
        'bearing_layer':    "Jusqu'à horizon porteur",
        'reinf':            'Armatures',
        'full_cage':        'Cage HA500B pleine longueur',
        'nb_piles_label':   'Nb pieux total',
        'est_geotech':      'Estimé — à confirmer par BET géotechnique',
        'deep_found_note':  'Fondations profondes = poste le plus coûteux après gros œuvre.',
        'found_cost_note':  'Impact prix fondations',
        'accel':            'Accélération ag',
        'nat_annex':        'Annexe nationale',
        'soil_factor':      'Facteur sol S',
        'soil_c':           'Sol type C — EC8 Tableau 3.2',
        'q_factor':         'Coefficient q',
        'period':           'Période T₁',
        'base_force':       'Force de base Fb',
        'dcl_comp':         'Conformité DCL',
        'add_analysis':     '⚠ Analyse complémentaire',
        'eng_note_label':   'Note de synthèse :',
        'strengths_label':  '✅ Points forts',
        'attention_label':  "⚠ Points d'attention",
        'rec_label':        'Recommandations :',
        'earthworks_item':  'Terrassement — décapage + fouilles méca.',
        'found_item':       'Fondations — pieux/semelles/radier béton armé',
        'masonry_item':     'Maçonnerie — agglos 15cm enduits 2 faces',
        'misc_item':        'Divers — joints, acrotères, réservations',
        'total_struct':     'TOTAL STRUCTURE',
        'low_val':          'VALEUR BASSE',
        'high_val':         'VALEUR HAUTE',
        'total_built':      'Surface bâtie totale',
        'cost_m2_built':    'Coût / m² bâti',
        'cost_m2_hab':      'Coût / m² habitable',
        'total_cost_struct':'COÛT TOTAL STRUCTURE',
        'struct_only':      'Structure seule — hors MEP, finitions, VRD',
        'hab_note':         'Surface habitable ≈ 78% surface bâtie',
        'estimate_note_short': 'Estimation ±15%',
        'grid':             'grille',
        'elu_comb':         'Combinaison ELU :',
        'footing_width':    'Largeur semelle',
        'square_sec':       'Section carrée',
        'depth':            'Profondeur',
        'below_frost':      'Hors gel + horizon porteur',
        # Footer disclaimer
        'disclaimer':   (
            'Document d\'assistance à l\'ingénierie — Version bêta ±15%. '
            'Doit être vérifié par un ingénieur habilité. '
            'Ne remplace pas l\'intervention légalement obligatoire d\'un bureau d\'études.'
        ),

        # Misc
        'surface_note': '* Surface bâtie estimée (emprise × niveaux) — à confirmer avec plans définitifs.',
        'built_area':   'Surface bâtie',
        'hab_area':     'Surface habitable',
        'footprint':    'Emprise',
        'levels':       'niveaux',
        'prices_note':  'Prix unitaires marché local 2026 (fournis-posés). Marge ±15%.',
        'indicator':    'INDICATEUR',
        'market_ref':   'RÉFÉRENCE MARCHÉ',
        'brand':        'Marque / Réf.',
        'brands':       'Marques recommandées',
        'basic_col':    'Basic (FCFA)',
        'hend_col':     'High-End',
        'luxury_col':   'Luxury',
        'pct_total':    '% TOTAL',
        'cost_m2':      'COÛT / m² BÂTI',
    },

    'en': {
        # Document titles
        'note_structure_title':     'Structural Calculation Note',
        'boq_structure_title':      'Bill of Quantities — Structure',
        'note_mep_title':           'MEP Calculation Note',
        'boq_mep_title':            'MEP BOQ — Detailed',
        'edge_title':               'EDGE Pre-assessment',
        'executif_title':           'Executive Summary Report',

        # Subtitles
        'subtitle_structure':       'Indicative calculations ±15% — To be verified by a licensed structural engineer.',
        'subtitle_boq':             'Local market unit prices 2026 (supply and install). Margin ±15%.',
        'subtitle_mep':             'Document suitable for contractor consultation.',
        'subtitle_edge':            'IFC EDGE Standard v3',
        'subtitle_executif':        'This document is intended for the project owner.',

        # Structure sections
        'project_data':             'PROJECT DATA',
        'hypotheses':               'ASSUMPTIONS AND DESIGN STANDARDS',
        'columns':                  'LOAD DESCENT — COLUMNS (EC2/EC8)',
        'beams':                    'BEAM DESIGN (EC2)',
        'slab':                     'SLAB DESIGN (EC2)',
        'partitions':               'PARTITIONS AND MASONRY',
        'foundations':              'FOUNDATION STUDY (EC7)',
        'seismic':                  'SEISMIC ANALYSIS (EC8 — EN 1998-1)',
        'analysis':                 'ANALYSIS AND RECOMMENDATIONS',
        'boq_section':              'BILL OF QUANTITIES — STRUCTURE',

        # Table headers
        'parameter':    'PARAMETER',
        'value':        'VALUE',
        'justif':       'JUSTIFICATION',
        'lot':          'Lot',
        'designation':  'Description',
        'qty':          'Qty',
        'unit':         'Unit',
        'pu':           'Unit price',
        'amount':       'Amount',
        'amount_low':   'Low amount',
        'amount_high':  'High amount',
        'notes':        'Notes',
        'level':        'Level',
        'section':      'Section',
        'rebars':       'Reinforcement',
        'rate':         'Steel ratio',
        'verif':        'Check',

        # Status labels
        'ok':           '✓ OK',
        'nok':          '✗ NOK',
        'compliant':    '✓ Compliant',
        'to_verify':    '⚠ To verify',
        'soon':         'Coming soon',

        # MEP sections
        'elec_section': 'ELECTRICAL BALANCE (NF C 15-100)',
        'plumb_section':'PLUMBING BALANCE (DTU 60.11)',
        'cvc_section':  'HVAC BALANCE (EN 12831 — ASHRAE 55)',
        'cf_section':   'LOW CURRENT SYSTEMS',
        'fire_section': 'FIRE SAFETY (IT 246)',
        'elev_section': 'LIFTS (EN 81-20/50)',
        'auto_section': 'BMS AUTOMATION',

        # EDGE
        'edge_scores':  'EDGE SCORES SUMMARY',
        'pillar':       'PILLAR',
        'score':        'PROJECT SCORE',
        'target':       'TARGET',
        'status':       'STATUS',
        'certifiable':  'CERTIFIABLE',
        'not_cert':     'NOT CERTIFIABLE',
        'energy':       'Energy',
        'water':        'Water',
        'materials':    'Materials',
        'action_plan':  'ACTION PLAN — OPTIMISATION TOWARDS CERTIFICATION',
        'pillar1':      'PILLAR 1 — ENERGY',
        'pillar2':      'PILLAR 2 — WATER',
        'pillar3':      'PILLAR 3 — MATERIALS',
        'measure':      'MEASURE',
        'gain':         'SAVING (%)',
        'impact':       'COST IMPACT',
        'action':       'ACTION',
        'cost':         'COST',
        'roi':          'ROI',

        # Executive report
        'project_sheet':    'PROJECT SHEET',
        'global_budget':    'GLOBAL BUDGET ESTIMATE',
        'edge_perf':        'ENVIRONMENTAL PERFORMANCE (EDGE IFC)',
        'key_points':       'KEY POINTS AND RECOMMENDATIONS',
        'body_of_work':     'TRADE',
        'total':            'TOTAL',
        'total_go':         'TOTAL STRUCTURAL WORKS',
        'finishes':         'Finishes (estimate)',
        'total_estimate':   'TOTAL ESTIMATED COST',

        # BOQ labels
        'installation':     'SITE INSTALLATION AND ORGANISATION',
        'earthworks':       'EARTHWORKS',
        'foundation_lot':   'FOUNDATIONS',
        'structure_lot':    'REINFORCED CONCRETE STRUCTURE',
        'masonry_lot':      'MASONRY, PARTITIONS AND RENDER',
        'waterproof_lot':   'WATERPROOFING AND INSULATION',
        'misc_lot':         'MISCELLANEOUS, CONTINGENCIES AND FEES',
        'recap':            'GENERAL SUMMARY',
        'sub_total':        'SUB-TOTAL',
        'grand_total':      'TOTAL EXCL. TAX',
        'low_range':        'LOW RANGE (-5%)',
        'high_range':       'HIGH RANGE (+15%)',

        # BOQ MEP lots
        'lot_elec':     'ELECTRICAL — POWER (NF C 15-100)',
        'lot_plumb':    'PLUMBING (DTU 60.11)',
        'lot_cvc':      'HVAC — AIR CONDITIONING AND VENTILATION (EN 12831)',
        'lot_cf':       'LOW CURRENT — NETWORK, CCTV, ACCESS CONTROL, INTERCOM',
        'lot_fire':     'FIRE SAFETY (IT 246)',
        'lot_elev':     'LIFTS AND GOODS LIFTS (EN 81-20/50)',
        'lot_auto':     'BMS AUTOMATION',


        'project':          'Project',
        'location':         'Location',
        'usage_label':      'Use',
        'levels_label':     'Levels',
        'spans':            'Spans',
        'bays':             'Bays',
        'concrete':         'Concrete',
        'steel':            'Steel',
        'soil':             'Admissible soil bearing',
        'sea_dist':         'Distance to sea',
        'loads':            'Loads G / Q',
        'seismic_zone':     'Seismic zone',
        'rc_label':         'Reinforced concrete',
        'seismic_label':    'Seismic',
        'perm_loads':       'Permanent loads G',
        'var_loads':        'Variable loads Q',
        'elu_combo':        'ULS combination',
        'foundations_label':'Foundations',
        'durability':       'Durability',
        'ned':              'NEd (kN)',
        'section_h':        'Section',
        'nb_bars':          'No. bars',
        'diam':             'Ø (mm)',
        'stirrup_d':        'Ø stir.',
        'stirrup_s':        'Stir. sp.',
        'ratio':            'ρ (%)',
        'nrd':              'NRd (kN)',
        'ratio_check':      'NEd/NRd',
        'rho_note':         'ρ = steel ratio (EC2: 0.1% ≤ ρ ≤ 4%) | NEd/NRd < 1 required',
        'b_mm':             'b (mm)',
        'h_mm':             'h (mm)',
        'as_inf':           'As bot (cm²)',
        'as_sup':           'As top (cm²)',
        'stirrups':         'Stirrups',
        'stir_sp':          'Stir. sp.',
        'span_m':           'Span (m)',
        'defl_check':       'Deflection check',
        'shear_check':      'Shear force',
        'beam_type':        'Beam',
        'span_label':       'span',
        'thickness':        'Thickness',
        'as_x':             'As x (cm²/m)',
        'as_y':             'As y (cm²/m)',
        'rebar_main':       'Main span reinforcement',
        'rebar_sec':        'Secondary span reinforcement',
        'adm_defl':         'Admissible deflection',
        'verif_label':      'Verification',
        'justif_label':     'Justification',
        'pile_diam':        'Pile diameter',
        'drilled':          'Bored pile',
        'pile_length':      'Pile length',
        'bearing_layer':    'To bearing stratum',
        'reinf':            'Reinforcement',
        'full_cage':        'HA500B full length cage',
        'nb_piles_label':   'Total no. piles',
        'est_geotech':      'Estimate — to be confirmed by geotechnical engineer',
        'deep_found_note':  'Deep foundations = most costly item after superstructure.',
        'found_cost_note':  'Foundation cost impact',
        'accel':            'Acceleration ag',
        'nat_annex':        'National annex',
        'soil_factor':      'Soil factor S',
        'soil_c':           'Soil type C — EC8 Table 3.2',
        'q_factor':         'Behaviour factor q',
        'period':           'Period T₁',
        'base_force':       'Base shear Fb',
        'dcl_comp':         'DCL compliance',
        'add_analysis':     '⚠ Additional analysis required',
        'eng_note_label':   "Engineer's summary note:",
        'strengths_label':  '✅ Key strengths',
        'attention_label':  '⚠ Points of attention',
        'rec_label':        'Recommendations:',
        'earthworks_item':  'Earthworks — stripping + mechanical excavation',
        'found_item':       'Foundations — bored piles / footings / raft',
        'masonry_item':     'Masonry — 15cm hollow blocks both faces rendered',
        'misc_item':        'Miscellaneous — joints, parapets, sleeves',
        'total_struct':     'TOTAL STRUCTURE',
        'low_val':          'LOW VALUE',
        'high_val':         'HIGH VALUE',
        'total_built':      'Total built area',
        'cost_m2_built':    'Cost / m² built',
        'cost_m2_hab':      'Cost / m² habitable',
        'total_cost_struct':'TOTAL STRUCTURE COST',
        'struct_only':      'Structure only — excl. MEP, finishes, utilities',
        'hab_note':         'Habitable area ≈ 78% of built area',
        'estimate_note_short': 'Estimate ±15%',
        'grid':             'grid',
        'elu_comb':         'ULS combination:',
        'footing_width':    'Footing width',
        'square_sec':       'Square section',
        'depth':            'Depth',
        'below_frost':      'Below frost line + bearing stratum',

        'project':          'Project',
        'location':         'Location',
        'usage_label':      'Use',
        'levels_label':     'Levels',
        'built_surface':    'Built area',
        'hab_surface':      'Habitable area',
        'spans':            'Spans',
        'bays':             'Bays',
        'concrete':         'Concrete',
        'steel':            'Steel',
        'soil':             'Admissible soil bearing',
        'sea_dist':         'Distance to sea',
        'loads':            'Loads G / Q',
        'seismic_zone':     'Seismic zone',
        'rc_label':         'Reinforced concrete',
        'seismic_label':    'Seismic',
        'perm_loads':       'Permanent loads G',
        'var_loads':        'Variable loads Q',
        'elu_combo':        'ULS combination',
        'foundations_label':'Foundations',
        'durability':       'Durability',
        'ned':              'NEd (kN)',
        'section_h':        'Section',
        'nb_bars':          'No. bars',
        'diam':             'Ø (mm)',
        'stirrup_d':        'Ø stir.',
        'stirrup_s':        'Stir. sp.',
        'ratio':            'ρ (%)',
        'nrd':              'NRd (kN)',
        'ratio_check':      'NEd/NRd',
        'rho_note':         'ρ = steel ratio (EC2: 0.1% ≤ ρ ≤ 4%) | NEd/NRd < 1 required',
        'b_mm':             'b (mm)',
        'h_mm':             'h (mm)',
        'as_inf':           'As bot (cm²)',
        'as_sup':           'As top (cm²)',
        'stirrups':         'Stirrups',
        'stir_sp':          'Stir. sp.',
        'span_m':           'Span (m)',
        'defl_check':       'Deflection check',
        'shear_check':      'Shear force',
        'beam_type':        'Beam',
        'span_label':       'span',
        'thickness':        'Thickness',
        'as_x':             'As x (cm²/m)',
        'as_y':             'As y (cm²/m)',
        'rebar_main':       'Main span reinforcement',
        'rebar_sec':        'Secondary span reinforcement',
        'adm_defl':         'Admissible deflection',
        'verif_label':      'Verification',
        'justif_label':     'Justification',
        'pile_diam':        'Pile diameter',
        'drilled':          'Bored pile',
        'pile_length':      'Pile length',
        'bearing_layer':    'To bearing stratum',
        'reinf':            'Reinforcement',
        'full_cage':        'HA500B full length cage',
        'nb_piles_label':   'Total no. piles',
        'est_geotech':      'Estimate — to be confirmed by geotechnical engineer',
        'deep_found_note':  'Deep foundations = most costly item after superstructure.',
        'found_cost_note':  'Foundation cost impact',
        'accel':            'Acceleration ag',
        'nat_annex':        'National annex',
        'soil_factor':      'Soil factor S',
        'soil_c':           'Soil type C — EC8 Table 3.2',
        'q_factor':         'Behaviour factor q',
        'period':           'Period T₁',
        'base_force':       'Base shear Fb',
        'dcl_comp':         'DCL compliance',
        'add_analysis':     '⚠ Additional analysis required',
        'eng_note_label':   "Engineer's summary note:",
        'strengths_label':  '✅ Key strengths',
        'attention_label':  '⚠ Points of attention',
        'rec_label':        'Recommendations:',
        'earthworks_item':  'Earthworks — stripping + mechanical excavation',
        'found_item':       'Foundations — bored piles / footings / raft',
        'masonry_item':     'Masonry — 15cm hollow blocks both faces rendered',
        'misc_item':        'Miscellaneous — joints, parapets, sleeves',
        'total_struct':     'TOTAL STRUCTURE',
        'low_val':          'LOW VALUE',
        'high_val':         'HIGH VALUE',
        'total_built':      'Total built area',
        'cost_m2_built':    'Cost / m² built',
        'cost_m2_hab':      'Cost / m² habitable',
        'total_cost_struct':'TOTAL STRUCTURE COST',
        'struct_only':      'Structure only — excl. MEP, finishes, utilities',
        'hab_note':         'Habitable area ≈ 78% of built area',
        'estimate_note_short': 'Estimate ±15%',
        'grid':             'grid',
        'elu_comb':         'ULS combination:',
        'footing_width':    'Footing width',
        'square_sec':       'Square section',
        'depth':            'Depth',
        'below_frost':      'Below frost line + bearing stratum',
        # Footer disclaimer
        'disclaimer':   (
            'Engineering assistance document — Beta version ±15%. '
            'Must be verified by a licensed engineer. '
            'Does not replace the legally required involvement of a certified engineering firm.'
        ),

        # Misc
        'surface_note': '* Built area estimated (footprint × levels) — to be confirmed with final plans.',
        'built_area':   'Built area',
        'hab_area':     'Habitable area',
        'footprint':    'Footprint',
        'levels':       'levels',
        'prices_note':  'Local market unit prices 2026 (supply and install). Margin ±15%.',
        'indicator':    'INDICATOR',
        'market_ref':   'MARKET REFERENCE',
        'brand':        'Brand / Ref.',
        'brands':       'Recommended brands',
        'basic_col':    'Basic',
        'hend_col':     'High-End',
        'luxury_col':   'Luxury',
        'pct_total':    '% TOTAL',
        'cost_m2':      'COST / m² BUILT',
    }
}

def get_strings(lang: str = 'fr') -> dict:
    return STRINGS.get(lang, STRINGS['fr'])
