"""
pdf_translate.py — Traduction post-génération des textes PDF
Ne modifie PAS les moteurs. Traduit uniquement les labels/textes dans les PDFs.
"""

FR_TO_EN = {
    # Structure
    "Note de calcul structure": "Structural Analysis Report",
    "Descente de charges": "Load Path Analysis",
    "Poteaux": "Columns",
    "Niveau": "Level",
    "Section": "Section",
    "Armatures longitudinales": "Longitudinal Reinforcement",
    "Cadres": "Stirrups",
    "Béton": "Concrete",
    "Fondations": "Foundations",
    "Recommandations": "Recommendations",
    "Conforme": "Compliant",
    "Non conforme": "Non-compliant",
    "Dimensionnement": "Design",
    "résidentiel": "residential",
    "bureau": "office",
    "commercial": "commercial",
    "hôtel": "hotel",
    "Sélection automatique": "Automatic selection",
    "distance mer": "distance to sea",
    "usage": "use",
    
    # BOQ
    "BOQ Structure": "Structural BOQ",
    "BOQ MEP": "MEP BOQ",
    "Désignation": "Description",
    "Unité": "Unit",
    "Quantité": "Quantity",
    "Prix unitaire": "Unit Price",
    "Montant": "Amount",
    "TOTAL": "TOTAL",
    "Béton armé": "Reinforced Concrete",
    "Acier": "Steel",
    "Coffrage": "Formwork",
    "Fondations profondes": "Deep Foundations",
    "Terrassement": "Earthwork",
    "Maçonnerie": "Masonry",
    "Estimation": "Estimate",
    
    # MEP
    "Note de calcul MEP": "MEP Analysis Report",
    "Électricité": "Electrical",
    "Plomberie": "Plumbing",
    "Sécurité incendie": "Fire Safety",
    "Ascenseurs": "Elevators",
    "Courants faibles": "Low Current Systems",
    "Automatisation": "Automation",
    "Puissance totale": "Total Power",
    "Transformateur": "Transformer",
    "Groupe électrogène": "Generator",
    "Nb compteurs": "No. meters",
    "Conso annuelle": "Annual Consumption",
    "Facture annuelle": "Annual Bill",
    "Nb logements": "No. units",
    "Besoin eau/jour": "Daily Water Need",
    "Volume citerne": "Tank Volume",
    "Surpresseur": "Booster Pump",
    "Facture eau/an": "Annual Water Bill",
    "Puissance frigo": "Cooling Capacity",
    "Catégorie ERP": "Building Category",
    "Détecteurs fumée": "Smoke Detectors",
    "Extincteurs": "Extinguishers",
    "Requis": "Required",
    "Non requis": "Not required",
    "Indicateur": "Indicator",
    "Valeur": "Value",
    "Paramètre": "Parameter",
    
    # EDGE
    "Pré-évaluation EDGE": "EDGE Pre-assessment",
    "Conformité EDGE": "EDGE Compliance",
    "Économie énergie": "Energy Savings",
    "Économie eau": "Water Savings",
    "Économie matériaux": "Materials Savings",
    "Certifiable": "Certifiable",
    "Non certifiable": "Not Certifiable",
    "Mesures énergie": "Energy Measures",
    "Mesures eau": "Water Measures",
    "Mesures matériaux": "Materials Measures",
    "Plan d'action": "Action Plan",
    "Coût de mise en conformité": "Compliance Cost",
    
    # Rapport exécutif
    "Rapport de synthèse exécutif": "Executive Summary Report",
    "Budget global estimé": "Estimated Global Budget",
    "Note de synthèse ingénieur": "Engineer's Summary",
    "Points forts": "Strengths",
    "Points d'attention": "Points of Attention",
    "Fiche projet": "Project Overview",
    "Performance environnementale": "Environmental Performance",
    "Points clés et recommandations": "Key Points and Recommendations",
    
    # Fiches techniques
    "Fiches techniques structure": "Structural Datasheets",
    "Fiches techniques MEP": "MEP Datasheets",
    "Fiche béton armé": "Reinforced Concrete Datasheet",
    "Fiche fondations": "Foundations Datasheet",
    "Fiche électricité": "Electrical Datasheet",
    "Fiche plomberie": "Plumbing Datasheet",
    
    # Communs
    "Ce document": "This document",
    "maître d'ouvrage": "project owner",
    "bureau d'études": "engineering firm",
    "avant travaux": "before construction",
    "niveaux": "levels",
    "logements": "units",
    "Surface bâtie": "Built Area",
    "Surface habitable": "Living Area",
    "Localisation": "Location",
    "Projet": "Project",
    "Hauteur": "Height",
    "Usage": "Use",
    "Certification EDGE": "EDGE Certification",
    "NOTE DE CALCUL STRUCTURE": "STRUCTURAL CALCULATION REPORT",
    "DESCENTE DE CHARGES": "LOAD PATH ANALYSIS",
    "POTEAUX": "COLUMNS",
    "DONNÉES DU PROJET": "PROJECT DATA",
    "HYPOTHÈSES ET NORMES DE CALCUL": "DESIGN ASSUMPTIONS AND STANDARDS",
    "PARAMÈTRE": "PARAMETER",
    "VALEUR": "VALUE",
    "Niveaux": "Levels",
    "Portées": "Spans",
    "Travées": "Bays",
    "Sol admissible": "Allowable soil",
    "Distance mer": "Distance to sea",
    "Charges G / Q": "Loads G / Q",
    "Zone sismique": "Seismic zone",
    "DOMAINE": "DOMAIN",
    "NORME": "STANDARD",
    "Séismique": "Seismic",
    "Charges perm. G": "Permanent loads G",
    "Charges var. Q": "Variable loads Q",
    "Combinaison ELU": "ULS combination",
    "Durabilité": "Durability",
    "Enrobage": "Cover",
    "ANALYSE STRUCTURELLE": "STRUCTURAL ANALYSIS",
    "DIMENSIONNEMENT DES POTEAUX": "COLUMN DESIGN",
    "FONDATIONS": "FOUNDATIONS",
    "MÉTRÉ ET ESTIMATION": "QUANTITIES AND ESTIMATE",
    "Lot": "Item",
    "Sous-total": "Subtotal",
    "TOTAL STRUCTURE": "TOTAL STRUCTURE",
    "fourchette basse": "low estimate",
    "fourchette haute": "high estimate",
    "SYNTHÈSE ET RECOMMANDATIONS": "SUMMARY AND RECOMMENDATIONS",
    "BOQ STRUCTURE": "STRUCTURAL BOQ",
    "PRÉ-ÉVALUATION EDGE": "EDGE PRE-ASSESSMENT",
    "RAPPORT DE SYNTHÈSE EXÉCUTIF": "EXECUTIVE SUMMARY REPORT",
    "FICHES TECHNIQUES STRUCTURE": "STRUCTURAL DATASHEETS",
    "FICHES TECHNIQUES MEP": "MEP DATASHEETS",
    "Exposition marine": "Marine exposure",
    "enrobage": "cover",
    "impératif": "mandatory",
    "Faire établir les plans d'exécution par un BET agréé avant travaux": "Have execution drawings prepared by a certified engineering firm before construction",
    "Prévoir essais béton sur site": "Plan for concrete testing on site",
    "au moins 3 éprouvettes par coulée": "at least 3 test specimens per pour",
    "Fondations profondes adaptées aux conditions de sol": "Deep foundations adapted to soil conditions",
    "Tous les poteaux vérifiés — structure conforme EC2": "All columns verified — EC2 compliant structure",
    "adapté à l'exposition et à la hauteur du bâtiment": "adapted to exposure and building height",
    "Vérifiée": "Verified",
    "Résidentiel": "Residential",
    "dimensionnée selon": "designed according to",
    "Tous les éléments vérifient les exigences de résistance": "All elements meet strength requirements",
    "Coût structure estimé": "Estimated structural cost",
    "Page": "Page",
    "Calculs indicatifs ±15%": "Indicative calculations ±15%",
    "À vérifier par un ingénieur structure habilité": "To be verified by a qualified structural engineer",
    "Dimensionnement cohérent pour un": "Consistent design for a",
    "niveaux à": "levels in",
    "ANALYSE ET RECOMMANDATIONS": "ANALYSIS AND RECOMMENDATIONS",
    "BORDEREAU DES QUANTITÉS ET DES PRIX — STRUCTURE": "BILL OF QUANTITIES AND PRICES — STRUCTURE",
    "DIMENSIONNEMENT POUTRES": "BEAM DESIGN",
    "DIMENSIONNEMENT DALLE": "SLAB DESIGN",
    "CLOISONS ET MAÇONNERIE": "PARTITIONS AND MASONRY",
    "ÉTUDE DES FONDATIONS": "FOUNDATION STUDY",
    "ANALYSE SISMIQUE": "SEISMIC ANALYSIS",
    "Montant bas": "Low estimate",
    "Montant haut": "High estimate",
    "INDICATEUR": "INDICATOR",
    "VALEUR BASSE": "LOW VALUE",
    "VALEUR HAUTE": "HIGH VALUE",
    "forfait": "lump sum",
    "décapage": "stripping",
    "fouilles": "excavation",
    "Étanchéité toiture-terrasse": "Roof waterproofing",
    "Divers": "Miscellaneous",
    "joints": "joints",
    "acrotères": "parapets",
    "réservations": "openings",
    "Coffrage toutes faces": "Formwork all faces",
    "fourni-posé": "supplied and installed",
    "COÛT TOTAL STRUCTURE": "TOTAL STRUCTURAL COST",
    "Surface bâtie totale": "Total built area",
    "Coût / m² bâti": "Cost / m² built",
    "Coût / m² habitable": "Cost / m² living area",
    "Structure seule — hors MEP, finitions, VRD": "Structure only — excl. MEP, finishes, utilities",
}

def translate_pdf_text(text: str) -> str:
    """Traduit un texte français en anglais en utilisant le dictionnaire."""
    result = text
    # Trier par longueur décroissante pour éviter les remplacements partiels
    for fr, en in sorted(FR_TO_EN.items(), key=lambda x: len(x[0]), reverse=True):
        result = result.replace(fr, en)
    return result
